/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

public class AdGroupCreateAdvancedSettingsInput {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("koaOptimizationSettings")
    private Optional<? extends AdGroupKoaOptimizationSettingsInput> koaOptimizationSettings;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("comscoreSettings")
    private Optional<? extends AdGroupComscoreSettingsInput> comscoreSettings;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("contractTargeting")
    private Optional<? extends AdGroupContractTargetingInput> contractTargeting;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dimensionalBiddingAutoOptimizationSettings")
    private JsonNullable<? extends List<List<DimensionalBiddingDimensions>>> dimensionalBiddingAutoOptimizationSettings;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("isUseClicksAsConversionsEnabled")
    private JsonNullable<Boolean> isUseClicksAsConversionsEnabled;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("isUseSecondaryConversionsEnabled")
    private JsonNullable<Boolean> isUseSecondaryConversionsEnabled;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("nielsenTrackingAttributes")
    private Optional<? extends AdGroupNielsenTrackingAttributesInput> nielsenTrackingAttributes;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("newFrequencyConfigs")
    private JsonNullable<? extends List<AdGroupNewFrequencyConfigInput>> newFrequencyConfigs;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("flights")
    private JsonNullable<? extends List<AdGroupCreateAdGroupFlightInput>> flights;

    @JsonCreator
    public AdGroupCreateAdvancedSettingsInput(
            @JsonProperty("koaOptimizationSettings") Optional<? extends AdGroupKoaOptimizationSettingsInput> koaOptimizationSettings,
            @JsonProperty("comscoreSettings") Optional<? extends AdGroupComscoreSettingsInput> comscoreSettings,
            @JsonProperty("contractTargeting") Optional<? extends AdGroupContractTargetingInput> contractTargeting,
            @JsonProperty("dimensionalBiddingAutoOptimizationSettings") JsonNullable<? extends List<List<DimensionalBiddingDimensions>>> dimensionalBiddingAutoOptimizationSettings,
            @JsonProperty("isUseClicksAsConversionsEnabled") JsonNullable<Boolean> isUseClicksAsConversionsEnabled,
            @JsonProperty("isUseSecondaryConversionsEnabled") JsonNullable<Boolean> isUseSecondaryConversionsEnabled,
            @JsonProperty("nielsenTrackingAttributes") Optional<? extends AdGroupNielsenTrackingAttributesInput> nielsenTrackingAttributes,
            @JsonProperty("newFrequencyConfigs") JsonNullable<? extends List<AdGroupNewFrequencyConfigInput>> newFrequencyConfigs,
            @JsonProperty("flights") JsonNullable<? extends List<AdGroupCreateAdGroupFlightInput>> flights) {
        Utils.checkNotNull(koaOptimizationSettings, "koaOptimizationSettings");
        Utils.checkNotNull(comscoreSettings, "comscoreSettings");
        Utils.checkNotNull(contractTargeting, "contractTargeting");
        Utils.checkNotNull(dimensionalBiddingAutoOptimizationSettings, "dimensionalBiddingAutoOptimizationSettings");
        Utils.checkNotNull(isUseClicksAsConversionsEnabled, "isUseClicksAsConversionsEnabled");
        Utils.checkNotNull(isUseSecondaryConversionsEnabled, "isUseSecondaryConversionsEnabled");
        Utils.checkNotNull(nielsenTrackingAttributes, "nielsenTrackingAttributes");
        Utils.checkNotNull(newFrequencyConfigs, "newFrequencyConfigs");
        Utils.checkNotNull(flights, "flights");
        this.koaOptimizationSettings = koaOptimizationSettings;
        this.comscoreSettings = comscoreSettings;
        this.contractTargeting = contractTargeting;
        this.dimensionalBiddingAutoOptimizationSettings = dimensionalBiddingAutoOptimizationSettings;
        this.isUseClicksAsConversionsEnabled = isUseClicksAsConversionsEnabled;
        this.isUseSecondaryConversionsEnabled = isUseSecondaryConversionsEnabled;
        this.nielsenTrackingAttributes = nielsenTrackingAttributes;
        this.newFrequencyConfigs = newFrequencyConfigs;
        this.flights = flights;
    }
    
    public AdGroupCreateAdvancedSettingsInput() {
        this(Optional.empty(), Optional.empty(), Optional.empty(), JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(), Optional.empty(), JsonNullable.undefined(), JsonNullable.undefined());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<AdGroupKoaOptimizationSettingsInput> koaOptimizationSettings() {
        return (Optional<AdGroupKoaOptimizationSettingsInput>) koaOptimizationSettings;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<AdGroupComscoreSettingsInput> comscoreSettings() {
        return (Optional<AdGroupComscoreSettingsInput>) comscoreSettings;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<AdGroupContractTargetingInput> contractTargeting() {
        return (Optional<AdGroupContractTargetingInput>) contractTargeting;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<List<List<DimensionalBiddingDimensions>>> dimensionalBiddingAutoOptimizationSettings() {
        return (JsonNullable<List<List<DimensionalBiddingDimensions>>>) dimensionalBiddingAutoOptimizationSettings;
    }

    @JsonIgnore
    public JsonNullable<Boolean> isUseClicksAsConversionsEnabled() {
        return isUseClicksAsConversionsEnabled;
    }

    @JsonIgnore
    public JsonNullable<Boolean> isUseSecondaryConversionsEnabled() {
        return isUseSecondaryConversionsEnabled;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<AdGroupNielsenTrackingAttributesInput> nielsenTrackingAttributes() {
        return (Optional<AdGroupNielsenTrackingAttributesInput>) nielsenTrackingAttributes;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<List<AdGroupNewFrequencyConfigInput>> newFrequencyConfigs() {
        return (JsonNullable<List<AdGroupNewFrequencyConfigInput>>) newFrequencyConfigs;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<List<AdGroupCreateAdGroupFlightInput>> flights() {
        return (JsonNullable<List<AdGroupCreateAdGroupFlightInput>>) flights;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public AdGroupCreateAdvancedSettingsInput withKoaOptimizationSettings(AdGroupKoaOptimizationSettingsInput koaOptimizationSettings) {
        Utils.checkNotNull(koaOptimizationSettings, "koaOptimizationSettings");
        this.koaOptimizationSettings = Optional.ofNullable(koaOptimizationSettings);
        return this;
    }

    public AdGroupCreateAdvancedSettingsInput withKoaOptimizationSettings(Optional<? extends AdGroupKoaOptimizationSettingsInput> koaOptimizationSettings) {
        Utils.checkNotNull(koaOptimizationSettings, "koaOptimizationSettings");
        this.koaOptimizationSettings = koaOptimizationSettings;
        return this;
    }

    public AdGroupCreateAdvancedSettingsInput withComscoreSettings(AdGroupComscoreSettingsInput comscoreSettings) {
        Utils.checkNotNull(comscoreSettings, "comscoreSettings");
        this.comscoreSettings = Optional.ofNullable(comscoreSettings);
        return this;
    }

    public AdGroupCreateAdvancedSettingsInput withComscoreSettings(Optional<? extends AdGroupComscoreSettingsInput> comscoreSettings) {
        Utils.checkNotNull(comscoreSettings, "comscoreSettings");
        this.comscoreSettings = comscoreSettings;
        return this;
    }

    public AdGroupCreateAdvancedSettingsInput withContractTargeting(AdGroupContractTargetingInput contractTargeting) {
        Utils.checkNotNull(contractTargeting, "contractTargeting");
        this.contractTargeting = Optional.ofNullable(contractTargeting);
        return this;
    }

    public AdGroupCreateAdvancedSettingsInput withContractTargeting(Optional<? extends AdGroupContractTargetingInput> contractTargeting) {
        Utils.checkNotNull(contractTargeting, "contractTargeting");
        this.contractTargeting = contractTargeting;
        return this;
    }

    public AdGroupCreateAdvancedSettingsInput withDimensionalBiddingAutoOptimizationSettings(List<List<DimensionalBiddingDimensions>> dimensionalBiddingAutoOptimizationSettings) {
        Utils.checkNotNull(dimensionalBiddingAutoOptimizationSettings, "dimensionalBiddingAutoOptimizationSettings");
        this.dimensionalBiddingAutoOptimizationSettings = JsonNullable.of(dimensionalBiddingAutoOptimizationSettings);
        return this;
    }

    public AdGroupCreateAdvancedSettingsInput withDimensionalBiddingAutoOptimizationSettings(JsonNullable<? extends List<List<DimensionalBiddingDimensions>>> dimensionalBiddingAutoOptimizationSettings) {
        Utils.checkNotNull(dimensionalBiddingAutoOptimizationSettings, "dimensionalBiddingAutoOptimizationSettings");
        this.dimensionalBiddingAutoOptimizationSettings = dimensionalBiddingAutoOptimizationSettings;
        return this;
    }

    public AdGroupCreateAdvancedSettingsInput withIsUseClicksAsConversionsEnabled(boolean isUseClicksAsConversionsEnabled) {
        Utils.checkNotNull(isUseClicksAsConversionsEnabled, "isUseClicksAsConversionsEnabled");
        this.isUseClicksAsConversionsEnabled = JsonNullable.of(isUseClicksAsConversionsEnabled);
        return this;
    }

    public AdGroupCreateAdvancedSettingsInput withIsUseClicksAsConversionsEnabled(JsonNullable<Boolean> isUseClicksAsConversionsEnabled) {
        Utils.checkNotNull(isUseClicksAsConversionsEnabled, "isUseClicksAsConversionsEnabled");
        this.isUseClicksAsConversionsEnabled = isUseClicksAsConversionsEnabled;
        return this;
    }

    public AdGroupCreateAdvancedSettingsInput withIsUseSecondaryConversionsEnabled(boolean isUseSecondaryConversionsEnabled) {
        Utils.checkNotNull(isUseSecondaryConversionsEnabled, "isUseSecondaryConversionsEnabled");
        this.isUseSecondaryConversionsEnabled = JsonNullable.of(isUseSecondaryConversionsEnabled);
        return this;
    }

    public AdGroupCreateAdvancedSettingsInput withIsUseSecondaryConversionsEnabled(JsonNullable<Boolean> isUseSecondaryConversionsEnabled) {
        Utils.checkNotNull(isUseSecondaryConversionsEnabled, "isUseSecondaryConversionsEnabled");
        this.isUseSecondaryConversionsEnabled = isUseSecondaryConversionsEnabled;
        return this;
    }

    public AdGroupCreateAdvancedSettingsInput withNielsenTrackingAttributes(AdGroupNielsenTrackingAttributesInput nielsenTrackingAttributes) {
        Utils.checkNotNull(nielsenTrackingAttributes, "nielsenTrackingAttributes");
        this.nielsenTrackingAttributes = Optional.ofNullable(nielsenTrackingAttributes);
        return this;
    }

    public AdGroupCreateAdvancedSettingsInput withNielsenTrackingAttributes(Optional<? extends AdGroupNielsenTrackingAttributesInput> nielsenTrackingAttributes) {
        Utils.checkNotNull(nielsenTrackingAttributes, "nielsenTrackingAttributes");
        this.nielsenTrackingAttributes = nielsenTrackingAttributes;
        return this;
    }

    public AdGroupCreateAdvancedSettingsInput withNewFrequencyConfigs(List<AdGroupNewFrequencyConfigInput> newFrequencyConfigs) {
        Utils.checkNotNull(newFrequencyConfigs, "newFrequencyConfigs");
        this.newFrequencyConfigs = JsonNullable.of(newFrequencyConfigs);
        return this;
    }

    public AdGroupCreateAdvancedSettingsInput withNewFrequencyConfigs(JsonNullable<? extends List<AdGroupNewFrequencyConfigInput>> newFrequencyConfigs) {
        Utils.checkNotNull(newFrequencyConfigs, "newFrequencyConfigs");
        this.newFrequencyConfigs = newFrequencyConfigs;
        return this;
    }

    public AdGroupCreateAdvancedSettingsInput withFlights(List<AdGroupCreateAdGroupFlightInput> flights) {
        Utils.checkNotNull(flights, "flights");
        this.flights = JsonNullable.of(flights);
        return this;
    }

    public AdGroupCreateAdvancedSettingsInput withFlights(JsonNullable<? extends List<AdGroupCreateAdGroupFlightInput>> flights) {
        Utils.checkNotNull(flights, "flights");
        this.flights = flights;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AdGroupCreateAdvancedSettingsInput other = (AdGroupCreateAdvancedSettingsInput) o;
        return 
            Objects.deepEquals(this.koaOptimizationSettings, other.koaOptimizationSettings) &&
            Objects.deepEquals(this.comscoreSettings, other.comscoreSettings) &&
            Objects.deepEquals(this.contractTargeting, other.contractTargeting) &&
            Objects.deepEquals(this.dimensionalBiddingAutoOptimizationSettings, other.dimensionalBiddingAutoOptimizationSettings) &&
            Objects.deepEquals(this.isUseClicksAsConversionsEnabled, other.isUseClicksAsConversionsEnabled) &&
            Objects.deepEquals(this.isUseSecondaryConversionsEnabled, other.isUseSecondaryConversionsEnabled) &&
            Objects.deepEquals(this.nielsenTrackingAttributes, other.nielsenTrackingAttributes) &&
            Objects.deepEquals(this.newFrequencyConfigs, other.newFrequencyConfigs) &&
            Objects.deepEquals(this.flights, other.flights);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            koaOptimizationSettings,
            comscoreSettings,
            contractTargeting,
            dimensionalBiddingAutoOptimizationSettings,
            isUseClicksAsConversionsEnabled,
            isUseSecondaryConversionsEnabled,
            nielsenTrackingAttributes,
            newFrequencyConfigs,
            flights);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AdGroupCreateAdvancedSettingsInput.class,
                "koaOptimizationSettings", koaOptimizationSettings,
                "comscoreSettings", comscoreSettings,
                "contractTargeting", contractTargeting,
                "dimensionalBiddingAutoOptimizationSettings", dimensionalBiddingAutoOptimizationSettings,
                "isUseClicksAsConversionsEnabled", isUseClicksAsConversionsEnabled,
                "isUseSecondaryConversionsEnabled", isUseSecondaryConversionsEnabled,
                "nielsenTrackingAttributes", nielsenTrackingAttributes,
                "newFrequencyConfigs", newFrequencyConfigs,
                "flights", flights);
    }
    
    public final static class Builder {
 
        private Optional<? extends AdGroupKoaOptimizationSettingsInput> koaOptimizationSettings = Optional.empty();
 
        private Optional<? extends AdGroupComscoreSettingsInput> comscoreSettings = Optional.empty();
 
        private Optional<? extends AdGroupContractTargetingInput> contractTargeting = Optional.empty();
 
        private JsonNullable<? extends List<List<DimensionalBiddingDimensions>>> dimensionalBiddingAutoOptimizationSettings = JsonNullable.undefined();
 
        private JsonNullable<Boolean> isUseClicksAsConversionsEnabled = JsonNullable.undefined();
 
        private JsonNullable<Boolean> isUseSecondaryConversionsEnabled = JsonNullable.undefined();
 
        private Optional<? extends AdGroupNielsenTrackingAttributesInput> nielsenTrackingAttributes = Optional.empty();
 
        private JsonNullable<? extends List<AdGroupNewFrequencyConfigInput>> newFrequencyConfigs = JsonNullable.undefined();
 
        private JsonNullable<? extends List<AdGroupCreateAdGroupFlightInput>> flights = JsonNullable.undefined();
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder koaOptimizationSettings(AdGroupKoaOptimizationSettingsInput koaOptimizationSettings) {
            Utils.checkNotNull(koaOptimizationSettings, "koaOptimizationSettings");
            this.koaOptimizationSettings = Optional.ofNullable(koaOptimizationSettings);
            return this;
        }

        public Builder koaOptimizationSettings(Optional<? extends AdGroupKoaOptimizationSettingsInput> koaOptimizationSettings) {
            Utils.checkNotNull(koaOptimizationSettings, "koaOptimizationSettings");
            this.koaOptimizationSettings = koaOptimizationSettings;
            return this;
        }

        public Builder comscoreSettings(AdGroupComscoreSettingsInput comscoreSettings) {
            Utils.checkNotNull(comscoreSettings, "comscoreSettings");
            this.comscoreSettings = Optional.ofNullable(comscoreSettings);
            return this;
        }

        public Builder comscoreSettings(Optional<? extends AdGroupComscoreSettingsInput> comscoreSettings) {
            Utils.checkNotNull(comscoreSettings, "comscoreSettings");
            this.comscoreSettings = comscoreSettings;
            return this;
        }

        public Builder contractTargeting(AdGroupContractTargetingInput contractTargeting) {
            Utils.checkNotNull(contractTargeting, "contractTargeting");
            this.contractTargeting = Optional.ofNullable(contractTargeting);
            return this;
        }

        public Builder contractTargeting(Optional<? extends AdGroupContractTargetingInput> contractTargeting) {
            Utils.checkNotNull(contractTargeting, "contractTargeting");
            this.contractTargeting = contractTargeting;
            return this;
        }

        public Builder dimensionalBiddingAutoOptimizationSettings(List<List<DimensionalBiddingDimensions>> dimensionalBiddingAutoOptimizationSettings) {
            Utils.checkNotNull(dimensionalBiddingAutoOptimizationSettings, "dimensionalBiddingAutoOptimizationSettings");
            this.dimensionalBiddingAutoOptimizationSettings = JsonNullable.of(dimensionalBiddingAutoOptimizationSettings);
            return this;
        }

        public Builder dimensionalBiddingAutoOptimizationSettings(JsonNullable<? extends List<List<DimensionalBiddingDimensions>>> dimensionalBiddingAutoOptimizationSettings) {
            Utils.checkNotNull(dimensionalBiddingAutoOptimizationSettings, "dimensionalBiddingAutoOptimizationSettings");
            this.dimensionalBiddingAutoOptimizationSettings = dimensionalBiddingAutoOptimizationSettings;
            return this;
        }

        public Builder isUseClicksAsConversionsEnabled(boolean isUseClicksAsConversionsEnabled) {
            Utils.checkNotNull(isUseClicksAsConversionsEnabled, "isUseClicksAsConversionsEnabled");
            this.isUseClicksAsConversionsEnabled = JsonNullable.of(isUseClicksAsConversionsEnabled);
            return this;
        }

        public Builder isUseClicksAsConversionsEnabled(JsonNullable<Boolean> isUseClicksAsConversionsEnabled) {
            Utils.checkNotNull(isUseClicksAsConversionsEnabled, "isUseClicksAsConversionsEnabled");
            this.isUseClicksAsConversionsEnabled = isUseClicksAsConversionsEnabled;
            return this;
        }

        public Builder isUseSecondaryConversionsEnabled(boolean isUseSecondaryConversionsEnabled) {
            Utils.checkNotNull(isUseSecondaryConversionsEnabled, "isUseSecondaryConversionsEnabled");
            this.isUseSecondaryConversionsEnabled = JsonNullable.of(isUseSecondaryConversionsEnabled);
            return this;
        }

        public Builder isUseSecondaryConversionsEnabled(JsonNullable<Boolean> isUseSecondaryConversionsEnabled) {
            Utils.checkNotNull(isUseSecondaryConversionsEnabled, "isUseSecondaryConversionsEnabled");
            this.isUseSecondaryConversionsEnabled = isUseSecondaryConversionsEnabled;
            return this;
        }

        public Builder nielsenTrackingAttributes(AdGroupNielsenTrackingAttributesInput nielsenTrackingAttributes) {
            Utils.checkNotNull(nielsenTrackingAttributes, "nielsenTrackingAttributes");
            this.nielsenTrackingAttributes = Optional.ofNullable(nielsenTrackingAttributes);
            return this;
        }

        public Builder nielsenTrackingAttributes(Optional<? extends AdGroupNielsenTrackingAttributesInput> nielsenTrackingAttributes) {
            Utils.checkNotNull(nielsenTrackingAttributes, "nielsenTrackingAttributes");
            this.nielsenTrackingAttributes = nielsenTrackingAttributes;
            return this;
        }

        public Builder newFrequencyConfigs(List<AdGroupNewFrequencyConfigInput> newFrequencyConfigs) {
            Utils.checkNotNull(newFrequencyConfigs, "newFrequencyConfigs");
            this.newFrequencyConfigs = JsonNullable.of(newFrequencyConfigs);
            return this;
        }

        public Builder newFrequencyConfigs(JsonNullable<? extends List<AdGroupNewFrequencyConfigInput>> newFrequencyConfigs) {
            Utils.checkNotNull(newFrequencyConfigs, "newFrequencyConfigs");
            this.newFrequencyConfigs = newFrequencyConfigs;
            return this;
        }

        public Builder flights(List<AdGroupCreateAdGroupFlightInput> flights) {
            Utils.checkNotNull(flights, "flights");
            this.flights = JsonNullable.of(flights);
            return this;
        }

        public Builder flights(JsonNullable<? extends List<AdGroupCreateAdGroupFlightInput>> flights) {
            Utils.checkNotNull(flights, "flights");
            this.flights = flights;
            return this;
        }
        
        public AdGroupCreateAdvancedSettingsInput build() {
            return new AdGroupCreateAdvancedSettingsInput(
                koaOptimizationSettings,
                comscoreSettings,
                contractTargeting,
                dimensionalBiddingAutoOptimizationSettings,
                isUseClicksAsConversionsEnabled,
                isUseSecondaryConversionsEnabled,
                nielsenTrackingAttributes,
                newFrequencyConfigs,
                flights);
        }
    }
}
