/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class AdGroupPayload {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("adGroup")
    private Optional<? extends AdGroupWorkflow> adGroup;

    @JsonCreator
    public AdGroupPayload(
            @JsonProperty("adGroup") Optional<? extends AdGroupWorkflow> adGroup) {
        Utils.checkNotNull(adGroup, "adGroup");
        this.adGroup = adGroup;
    }
    
    public AdGroupPayload() {
        this(Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<AdGroupWorkflow> adGroup() {
        return (Optional<AdGroupWorkflow>) adGroup;
    }

    public static Builder builder() {
        return new Builder();
    }


    public AdGroupPayload withAdGroup(AdGroupWorkflow adGroup) {
        Utils.checkNotNull(adGroup, "adGroup");
        this.adGroup = Optional.ofNullable(adGroup);
        return this;
    }


    public AdGroupPayload withAdGroup(Optional<? extends AdGroupWorkflow> adGroup) {
        Utils.checkNotNull(adGroup, "adGroup");
        this.adGroup = adGroup;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AdGroupPayload other = (AdGroupPayload) o;
        return 
            Utils.enhancedDeepEquals(this.adGroup, other.adGroup);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            adGroup);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AdGroupPayload.class,
                "adGroup", adGroup);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends AdGroupWorkflow> adGroup = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder adGroup(AdGroupWorkflow adGroup) {
            Utils.checkNotNull(adGroup, "adGroup");
            this.adGroup = Optional.ofNullable(adGroup);
            return this;
        }

        public Builder adGroup(Optional<? extends AdGroupWorkflow> adGroup) {
            Utils.checkNotNull(adGroup, "adGroup");
            this.adGroup = adGroup;
            return this;
        }

        public AdGroupPayload build() {

            return new AdGroupPayload(
                adGroup);
        }

    }
}
