/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

public class AdGroupBulkUpdateWorkflowInputWithValidation {

    @JsonInclude(Include.ALWAYS)
    @JsonProperty("input")
    private Optional<? extends List<AdGroupUpdateWorkflowInput>> input;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("validateInputOnly")
    private JsonNullable<Boolean> validateInputOnly;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("callbackInput")
    private Optional<? extends WorkflowCallbackInput> callbackInput;

    @JsonCreator
    public AdGroupBulkUpdateWorkflowInputWithValidation(
            @JsonProperty("input") Optional<? extends List<AdGroupUpdateWorkflowInput>> input,
            @JsonProperty("validateInputOnly") JsonNullable<Boolean> validateInputOnly,
            @JsonProperty("callbackInput") Optional<? extends WorkflowCallbackInput> callbackInput) {
        Utils.checkNotNull(input, "input");
        Utils.checkNotNull(validateInputOnly, "validateInputOnly");
        Utils.checkNotNull(callbackInput, "callbackInput");
        this.input = input;
        this.validateInputOnly = validateInputOnly;
        this.callbackInput = callbackInput;
    }
    
    public AdGroupBulkUpdateWorkflowInputWithValidation() {
        this(Optional.empty(), JsonNullable.undefined(), Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<AdGroupUpdateWorkflowInput>> input() {
        return (Optional<List<AdGroupUpdateWorkflowInput>>) input;
    }

    @JsonIgnore
    public JsonNullable<Boolean> validateInputOnly() {
        return validateInputOnly;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<WorkflowCallbackInput> callbackInput() {
        return (Optional<WorkflowCallbackInput>) callbackInput;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public AdGroupBulkUpdateWorkflowInputWithValidation withInput(List<AdGroupUpdateWorkflowInput> input) {
        Utils.checkNotNull(input, "input");
        this.input = Optional.ofNullable(input);
        return this;
    }

    public AdGroupBulkUpdateWorkflowInputWithValidation withInput(Optional<? extends List<AdGroupUpdateWorkflowInput>> input) {
        Utils.checkNotNull(input, "input");
        this.input = input;
        return this;
    }

    public AdGroupBulkUpdateWorkflowInputWithValidation withValidateInputOnly(boolean validateInputOnly) {
        Utils.checkNotNull(validateInputOnly, "validateInputOnly");
        this.validateInputOnly = JsonNullable.of(validateInputOnly);
        return this;
    }

    public AdGroupBulkUpdateWorkflowInputWithValidation withValidateInputOnly(JsonNullable<Boolean> validateInputOnly) {
        Utils.checkNotNull(validateInputOnly, "validateInputOnly");
        this.validateInputOnly = validateInputOnly;
        return this;
    }

    public AdGroupBulkUpdateWorkflowInputWithValidation withCallbackInput(WorkflowCallbackInput callbackInput) {
        Utils.checkNotNull(callbackInput, "callbackInput");
        this.callbackInput = Optional.ofNullable(callbackInput);
        return this;
    }

    public AdGroupBulkUpdateWorkflowInputWithValidation withCallbackInput(Optional<? extends WorkflowCallbackInput> callbackInput) {
        Utils.checkNotNull(callbackInput, "callbackInput");
        this.callbackInput = callbackInput;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AdGroupBulkUpdateWorkflowInputWithValidation other = (AdGroupBulkUpdateWorkflowInputWithValidation) o;
        return 
            Objects.deepEquals(this.input, other.input) &&
            Objects.deepEquals(this.validateInputOnly, other.validateInputOnly) &&
            Objects.deepEquals(this.callbackInput, other.callbackInput);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            input,
            validateInputOnly,
            callbackInput);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AdGroupBulkUpdateWorkflowInputWithValidation.class,
                "input", input,
                "validateInputOnly", validateInputOnly,
                "callbackInput", callbackInput);
    }
    
    public final static class Builder {
 
        private Optional<? extends List<AdGroupUpdateWorkflowInput>> input = Optional.empty();
 
        private JsonNullable<Boolean> validateInputOnly = JsonNullable.undefined();
 
        private Optional<? extends WorkflowCallbackInput> callbackInput = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder input(List<AdGroupUpdateWorkflowInput> input) {
            Utils.checkNotNull(input, "input");
            this.input = Optional.ofNullable(input);
            return this;
        }

        public Builder input(Optional<? extends List<AdGroupUpdateWorkflowInput>> input) {
            Utils.checkNotNull(input, "input");
            this.input = input;
            return this;
        }

        public Builder validateInputOnly(boolean validateInputOnly) {
            Utils.checkNotNull(validateInputOnly, "validateInputOnly");
            this.validateInputOnly = JsonNullable.of(validateInputOnly);
            return this;
        }

        public Builder validateInputOnly(JsonNullable<Boolean> validateInputOnly) {
            Utils.checkNotNull(validateInputOnly, "validateInputOnly");
            this.validateInputOnly = validateInputOnly;
            return this;
        }

        public Builder callbackInput(WorkflowCallbackInput callbackInput) {
            Utils.checkNotNull(callbackInput, "callbackInput");
            this.callbackInput = Optional.ofNullable(callbackInput);
            return this;
        }

        public Builder callbackInput(Optional<? extends WorkflowCallbackInput> callbackInput) {
            Utils.checkNotNull(callbackInput, "callbackInput");
            this.callbackInput = callbackInput;
            return this;
        }
        
        public AdGroupBulkUpdateWorkflowInputWithValidation build() {
            return new AdGroupBulkUpdateWorkflowInputWithValidation(
                input,
                validateInputOnly,
                callbackInput);
        }
    }
}
