/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapitools.jackson.nullable.JsonNullable;

public class AdGroupROIGoal {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("maximizeReach")
    private JsonNullable<Boolean> maximizeReach;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("maximizeLtvIncrementalReach")
    private JsonNullable<Boolean> maximizeLtvIncrementalReach;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cpcInAdvertiserCurrency")
    private JsonNullable<Double> cpcInAdvertiserCurrency;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ctrInPercent")
    private JsonNullable<Double> ctrInPercent;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("nielsenOTPInPercent")
    private JsonNullable<Double> nielsenOTPInPercent;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cpaInAdvertiserCurrency")
    private JsonNullable<Double> cpaInAdvertiserCurrency;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("returnOnAdSpendPercent")
    private JsonNullable<Double> returnOnAdSpendPercent;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("vcrInPercent")
    private JsonNullable<Double> vcrInPercent;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("viewabilityInPercent")
    private JsonNullable<Double> viewabilityInPercent;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("vcpmInAdvertiserCurrency")
    private JsonNullable<Double> vcpmInAdvertiserCurrency;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cpcvInAdvertiserCurrency")
    private JsonNullable<Double> cpcvInAdvertiserCurrency;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("miaozhenOTPInPercent")
    private JsonNullable<Double> miaozhenOTPInPercent;

    @JsonCreator
    public AdGroupROIGoal(
            @JsonProperty("maximizeReach") JsonNullable<Boolean> maximizeReach,
            @JsonProperty("maximizeLtvIncrementalReach") JsonNullable<Boolean> maximizeLtvIncrementalReach,
            @JsonProperty("cpcInAdvertiserCurrency") JsonNullable<Double> cpcInAdvertiserCurrency,
            @JsonProperty("ctrInPercent") JsonNullable<Double> ctrInPercent,
            @JsonProperty("nielsenOTPInPercent") JsonNullable<Double> nielsenOTPInPercent,
            @JsonProperty("cpaInAdvertiserCurrency") JsonNullable<Double> cpaInAdvertiserCurrency,
            @JsonProperty("returnOnAdSpendPercent") JsonNullable<Double> returnOnAdSpendPercent,
            @JsonProperty("vcrInPercent") JsonNullable<Double> vcrInPercent,
            @JsonProperty("viewabilityInPercent") JsonNullable<Double> viewabilityInPercent,
            @JsonProperty("vcpmInAdvertiserCurrency") JsonNullable<Double> vcpmInAdvertiserCurrency,
            @JsonProperty("cpcvInAdvertiserCurrency") JsonNullable<Double> cpcvInAdvertiserCurrency,
            @JsonProperty("miaozhenOTPInPercent") JsonNullable<Double> miaozhenOTPInPercent) {
        Utils.checkNotNull(maximizeReach, "maximizeReach");
        Utils.checkNotNull(maximizeLtvIncrementalReach, "maximizeLtvIncrementalReach");
        Utils.checkNotNull(cpcInAdvertiserCurrency, "cpcInAdvertiserCurrency");
        Utils.checkNotNull(ctrInPercent, "ctrInPercent");
        Utils.checkNotNull(nielsenOTPInPercent, "nielsenOTPInPercent");
        Utils.checkNotNull(cpaInAdvertiserCurrency, "cpaInAdvertiserCurrency");
        Utils.checkNotNull(returnOnAdSpendPercent, "returnOnAdSpendPercent");
        Utils.checkNotNull(vcrInPercent, "vcrInPercent");
        Utils.checkNotNull(viewabilityInPercent, "viewabilityInPercent");
        Utils.checkNotNull(vcpmInAdvertiserCurrency, "vcpmInAdvertiserCurrency");
        Utils.checkNotNull(cpcvInAdvertiserCurrency, "cpcvInAdvertiserCurrency");
        Utils.checkNotNull(miaozhenOTPInPercent, "miaozhenOTPInPercent");
        this.maximizeReach = maximizeReach;
        this.maximizeLtvIncrementalReach = maximizeLtvIncrementalReach;
        this.cpcInAdvertiserCurrency = cpcInAdvertiserCurrency;
        this.ctrInPercent = ctrInPercent;
        this.nielsenOTPInPercent = nielsenOTPInPercent;
        this.cpaInAdvertiserCurrency = cpaInAdvertiserCurrency;
        this.returnOnAdSpendPercent = returnOnAdSpendPercent;
        this.vcrInPercent = vcrInPercent;
        this.viewabilityInPercent = viewabilityInPercent;
        this.vcpmInAdvertiserCurrency = vcpmInAdvertiserCurrency;
        this.cpcvInAdvertiserCurrency = cpcvInAdvertiserCurrency;
        this.miaozhenOTPInPercent = miaozhenOTPInPercent;
    }
    
    public AdGroupROIGoal() {
        this(JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined());
    }

    @JsonIgnore
    public JsonNullable<Boolean> maximizeReach() {
        return maximizeReach;
    }

    @JsonIgnore
    public JsonNullable<Boolean> maximizeLtvIncrementalReach() {
        return maximizeLtvIncrementalReach;
    }

    @JsonIgnore
    public JsonNullable<Double> cpcInAdvertiserCurrency() {
        return cpcInAdvertiserCurrency;
    }

    @JsonIgnore
    public JsonNullable<Double> ctrInPercent() {
        return ctrInPercent;
    }

    @JsonIgnore
    public JsonNullable<Double> nielsenOTPInPercent() {
        return nielsenOTPInPercent;
    }

    @JsonIgnore
    public JsonNullable<Double> cpaInAdvertiserCurrency() {
        return cpaInAdvertiserCurrency;
    }

    @JsonIgnore
    public JsonNullable<Double> returnOnAdSpendPercent() {
        return returnOnAdSpendPercent;
    }

    @JsonIgnore
    public JsonNullable<Double> vcrInPercent() {
        return vcrInPercent;
    }

    @JsonIgnore
    public JsonNullable<Double> viewabilityInPercent() {
        return viewabilityInPercent;
    }

    @JsonIgnore
    public JsonNullable<Double> vcpmInAdvertiserCurrency() {
        return vcpmInAdvertiserCurrency;
    }

    @JsonIgnore
    public JsonNullable<Double> cpcvInAdvertiserCurrency() {
        return cpcvInAdvertiserCurrency;
    }

    @JsonIgnore
    public JsonNullable<Double> miaozhenOTPInPercent() {
        return miaozhenOTPInPercent;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public AdGroupROIGoal withMaximizeReach(boolean maximizeReach) {
        Utils.checkNotNull(maximizeReach, "maximizeReach");
        this.maximizeReach = JsonNullable.of(maximizeReach);
        return this;
    }

    public AdGroupROIGoal withMaximizeReach(JsonNullable<Boolean> maximizeReach) {
        Utils.checkNotNull(maximizeReach, "maximizeReach");
        this.maximizeReach = maximizeReach;
        return this;
    }

    public AdGroupROIGoal withMaximizeLtvIncrementalReach(boolean maximizeLtvIncrementalReach) {
        Utils.checkNotNull(maximizeLtvIncrementalReach, "maximizeLtvIncrementalReach");
        this.maximizeLtvIncrementalReach = JsonNullable.of(maximizeLtvIncrementalReach);
        return this;
    }

    public AdGroupROIGoal withMaximizeLtvIncrementalReach(JsonNullable<Boolean> maximizeLtvIncrementalReach) {
        Utils.checkNotNull(maximizeLtvIncrementalReach, "maximizeLtvIncrementalReach");
        this.maximizeLtvIncrementalReach = maximizeLtvIncrementalReach;
        return this;
    }

    public AdGroupROIGoal withCpcInAdvertiserCurrency(double cpcInAdvertiserCurrency) {
        Utils.checkNotNull(cpcInAdvertiserCurrency, "cpcInAdvertiserCurrency");
        this.cpcInAdvertiserCurrency = JsonNullable.of(cpcInAdvertiserCurrency);
        return this;
    }

    public AdGroupROIGoal withCpcInAdvertiserCurrency(JsonNullable<Double> cpcInAdvertiserCurrency) {
        Utils.checkNotNull(cpcInAdvertiserCurrency, "cpcInAdvertiserCurrency");
        this.cpcInAdvertiserCurrency = cpcInAdvertiserCurrency;
        return this;
    }

    public AdGroupROIGoal withCtrInPercent(double ctrInPercent) {
        Utils.checkNotNull(ctrInPercent, "ctrInPercent");
        this.ctrInPercent = JsonNullable.of(ctrInPercent);
        return this;
    }

    public AdGroupROIGoal withCtrInPercent(JsonNullable<Double> ctrInPercent) {
        Utils.checkNotNull(ctrInPercent, "ctrInPercent");
        this.ctrInPercent = ctrInPercent;
        return this;
    }

    public AdGroupROIGoal withNielsenOTPInPercent(double nielsenOTPInPercent) {
        Utils.checkNotNull(nielsenOTPInPercent, "nielsenOTPInPercent");
        this.nielsenOTPInPercent = JsonNullable.of(nielsenOTPInPercent);
        return this;
    }

    public AdGroupROIGoal withNielsenOTPInPercent(JsonNullable<Double> nielsenOTPInPercent) {
        Utils.checkNotNull(nielsenOTPInPercent, "nielsenOTPInPercent");
        this.nielsenOTPInPercent = nielsenOTPInPercent;
        return this;
    }

    public AdGroupROIGoal withCpaInAdvertiserCurrency(double cpaInAdvertiserCurrency) {
        Utils.checkNotNull(cpaInAdvertiserCurrency, "cpaInAdvertiserCurrency");
        this.cpaInAdvertiserCurrency = JsonNullable.of(cpaInAdvertiserCurrency);
        return this;
    }

    public AdGroupROIGoal withCpaInAdvertiserCurrency(JsonNullable<Double> cpaInAdvertiserCurrency) {
        Utils.checkNotNull(cpaInAdvertiserCurrency, "cpaInAdvertiserCurrency");
        this.cpaInAdvertiserCurrency = cpaInAdvertiserCurrency;
        return this;
    }

    public AdGroupROIGoal withReturnOnAdSpendPercent(double returnOnAdSpendPercent) {
        Utils.checkNotNull(returnOnAdSpendPercent, "returnOnAdSpendPercent");
        this.returnOnAdSpendPercent = JsonNullable.of(returnOnAdSpendPercent);
        return this;
    }

    public AdGroupROIGoal withReturnOnAdSpendPercent(JsonNullable<Double> returnOnAdSpendPercent) {
        Utils.checkNotNull(returnOnAdSpendPercent, "returnOnAdSpendPercent");
        this.returnOnAdSpendPercent = returnOnAdSpendPercent;
        return this;
    }

    public AdGroupROIGoal withVcrInPercent(double vcrInPercent) {
        Utils.checkNotNull(vcrInPercent, "vcrInPercent");
        this.vcrInPercent = JsonNullable.of(vcrInPercent);
        return this;
    }

    public AdGroupROIGoal withVcrInPercent(JsonNullable<Double> vcrInPercent) {
        Utils.checkNotNull(vcrInPercent, "vcrInPercent");
        this.vcrInPercent = vcrInPercent;
        return this;
    }

    public AdGroupROIGoal withViewabilityInPercent(double viewabilityInPercent) {
        Utils.checkNotNull(viewabilityInPercent, "viewabilityInPercent");
        this.viewabilityInPercent = JsonNullable.of(viewabilityInPercent);
        return this;
    }

    public AdGroupROIGoal withViewabilityInPercent(JsonNullable<Double> viewabilityInPercent) {
        Utils.checkNotNull(viewabilityInPercent, "viewabilityInPercent");
        this.viewabilityInPercent = viewabilityInPercent;
        return this;
    }

    public AdGroupROIGoal withVcpmInAdvertiserCurrency(double vcpmInAdvertiserCurrency) {
        Utils.checkNotNull(vcpmInAdvertiserCurrency, "vcpmInAdvertiserCurrency");
        this.vcpmInAdvertiserCurrency = JsonNullable.of(vcpmInAdvertiserCurrency);
        return this;
    }

    public AdGroupROIGoal withVcpmInAdvertiserCurrency(JsonNullable<Double> vcpmInAdvertiserCurrency) {
        Utils.checkNotNull(vcpmInAdvertiserCurrency, "vcpmInAdvertiserCurrency");
        this.vcpmInAdvertiserCurrency = vcpmInAdvertiserCurrency;
        return this;
    }

    public AdGroupROIGoal withCpcvInAdvertiserCurrency(double cpcvInAdvertiserCurrency) {
        Utils.checkNotNull(cpcvInAdvertiserCurrency, "cpcvInAdvertiserCurrency");
        this.cpcvInAdvertiserCurrency = JsonNullable.of(cpcvInAdvertiserCurrency);
        return this;
    }

    public AdGroupROIGoal withCpcvInAdvertiserCurrency(JsonNullable<Double> cpcvInAdvertiserCurrency) {
        Utils.checkNotNull(cpcvInAdvertiserCurrency, "cpcvInAdvertiserCurrency");
        this.cpcvInAdvertiserCurrency = cpcvInAdvertiserCurrency;
        return this;
    }

    public AdGroupROIGoal withMiaozhenOTPInPercent(double miaozhenOTPInPercent) {
        Utils.checkNotNull(miaozhenOTPInPercent, "miaozhenOTPInPercent");
        this.miaozhenOTPInPercent = JsonNullable.of(miaozhenOTPInPercent);
        return this;
    }

    public AdGroupROIGoal withMiaozhenOTPInPercent(JsonNullable<Double> miaozhenOTPInPercent) {
        Utils.checkNotNull(miaozhenOTPInPercent, "miaozhenOTPInPercent");
        this.miaozhenOTPInPercent = miaozhenOTPInPercent;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AdGroupROIGoal other = (AdGroupROIGoal) o;
        return 
            Objects.deepEquals(this.maximizeReach, other.maximizeReach) &&
            Objects.deepEquals(this.maximizeLtvIncrementalReach, other.maximizeLtvIncrementalReach) &&
            Objects.deepEquals(this.cpcInAdvertiserCurrency, other.cpcInAdvertiserCurrency) &&
            Objects.deepEquals(this.ctrInPercent, other.ctrInPercent) &&
            Objects.deepEquals(this.nielsenOTPInPercent, other.nielsenOTPInPercent) &&
            Objects.deepEquals(this.cpaInAdvertiserCurrency, other.cpaInAdvertiserCurrency) &&
            Objects.deepEquals(this.returnOnAdSpendPercent, other.returnOnAdSpendPercent) &&
            Objects.deepEquals(this.vcrInPercent, other.vcrInPercent) &&
            Objects.deepEquals(this.viewabilityInPercent, other.viewabilityInPercent) &&
            Objects.deepEquals(this.vcpmInAdvertiserCurrency, other.vcpmInAdvertiserCurrency) &&
            Objects.deepEquals(this.cpcvInAdvertiserCurrency, other.cpcvInAdvertiserCurrency) &&
            Objects.deepEquals(this.miaozhenOTPInPercent, other.miaozhenOTPInPercent);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            maximizeReach,
            maximizeLtvIncrementalReach,
            cpcInAdvertiserCurrency,
            ctrInPercent,
            nielsenOTPInPercent,
            cpaInAdvertiserCurrency,
            returnOnAdSpendPercent,
            vcrInPercent,
            viewabilityInPercent,
            vcpmInAdvertiserCurrency,
            cpcvInAdvertiserCurrency,
            miaozhenOTPInPercent);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AdGroupROIGoal.class,
                "maximizeReach", maximizeReach,
                "maximizeLtvIncrementalReach", maximizeLtvIncrementalReach,
                "cpcInAdvertiserCurrency", cpcInAdvertiserCurrency,
                "ctrInPercent", ctrInPercent,
                "nielsenOTPInPercent", nielsenOTPInPercent,
                "cpaInAdvertiserCurrency", cpaInAdvertiserCurrency,
                "returnOnAdSpendPercent", returnOnAdSpendPercent,
                "vcrInPercent", vcrInPercent,
                "viewabilityInPercent", viewabilityInPercent,
                "vcpmInAdvertiserCurrency", vcpmInAdvertiserCurrency,
                "cpcvInAdvertiserCurrency", cpcvInAdvertiserCurrency,
                "miaozhenOTPInPercent", miaozhenOTPInPercent);
    }
    
    public final static class Builder {
 
        private JsonNullable<Boolean> maximizeReach = JsonNullable.undefined();
 
        private JsonNullable<Boolean> maximizeLtvIncrementalReach = JsonNullable.undefined();
 
        private JsonNullable<Double> cpcInAdvertiserCurrency = JsonNullable.undefined();
 
        private JsonNullable<Double> ctrInPercent = JsonNullable.undefined();
 
        private JsonNullable<Double> nielsenOTPInPercent = JsonNullable.undefined();
 
        private JsonNullable<Double> cpaInAdvertiserCurrency = JsonNullable.undefined();
 
        private JsonNullable<Double> returnOnAdSpendPercent = JsonNullable.undefined();
 
        private JsonNullable<Double> vcrInPercent = JsonNullable.undefined();
 
        private JsonNullable<Double> viewabilityInPercent = JsonNullable.undefined();
 
        private JsonNullable<Double> vcpmInAdvertiserCurrency = JsonNullable.undefined();
 
        private JsonNullable<Double> cpcvInAdvertiserCurrency = JsonNullable.undefined();
 
        private JsonNullable<Double> miaozhenOTPInPercent = JsonNullable.undefined();
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder maximizeReach(boolean maximizeReach) {
            Utils.checkNotNull(maximizeReach, "maximizeReach");
            this.maximizeReach = JsonNullable.of(maximizeReach);
            return this;
        }

        public Builder maximizeReach(JsonNullable<Boolean> maximizeReach) {
            Utils.checkNotNull(maximizeReach, "maximizeReach");
            this.maximizeReach = maximizeReach;
            return this;
        }

        public Builder maximizeLtvIncrementalReach(boolean maximizeLtvIncrementalReach) {
            Utils.checkNotNull(maximizeLtvIncrementalReach, "maximizeLtvIncrementalReach");
            this.maximizeLtvIncrementalReach = JsonNullable.of(maximizeLtvIncrementalReach);
            return this;
        }

        public Builder maximizeLtvIncrementalReach(JsonNullable<Boolean> maximizeLtvIncrementalReach) {
            Utils.checkNotNull(maximizeLtvIncrementalReach, "maximizeLtvIncrementalReach");
            this.maximizeLtvIncrementalReach = maximizeLtvIncrementalReach;
            return this;
        }

        public Builder cpcInAdvertiserCurrency(double cpcInAdvertiserCurrency) {
            Utils.checkNotNull(cpcInAdvertiserCurrency, "cpcInAdvertiserCurrency");
            this.cpcInAdvertiserCurrency = JsonNullable.of(cpcInAdvertiserCurrency);
            return this;
        }

        public Builder cpcInAdvertiserCurrency(JsonNullable<Double> cpcInAdvertiserCurrency) {
            Utils.checkNotNull(cpcInAdvertiserCurrency, "cpcInAdvertiserCurrency");
            this.cpcInAdvertiserCurrency = cpcInAdvertiserCurrency;
            return this;
        }

        public Builder ctrInPercent(double ctrInPercent) {
            Utils.checkNotNull(ctrInPercent, "ctrInPercent");
            this.ctrInPercent = JsonNullable.of(ctrInPercent);
            return this;
        }

        public Builder ctrInPercent(JsonNullable<Double> ctrInPercent) {
            Utils.checkNotNull(ctrInPercent, "ctrInPercent");
            this.ctrInPercent = ctrInPercent;
            return this;
        }

        public Builder nielsenOTPInPercent(double nielsenOTPInPercent) {
            Utils.checkNotNull(nielsenOTPInPercent, "nielsenOTPInPercent");
            this.nielsenOTPInPercent = JsonNullable.of(nielsenOTPInPercent);
            return this;
        }

        public Builder nielsenOTPInPercent(JsonNullable<Double> nielsenOTPInPercent) {
            Utils.checkNotNull(nielsenOTPInPercent, "nielsenOTPInPercent");
            this.nielsenOTPInPercent = nielsenOTPInPercent;
            return this;
        }

        public Builder cpaInAdvertiserCurrency(double cpaInAdvertiserCurrency) {
            Utils.checkNotNull(cpaInAdvertiserCurrency, "cpaInAdvertiserCurrency");
            this.cpaInAdvertiserCurrency = JsonNullable.of(cpaInAdvertiserCurrency);
            return this;
        }

        public Builder cpaInAdvertiserCurrency(JsonNullable<Double> cpaInAdvertiserCurrency) {
            Utils.checkNotNull(cpaInAdvertiserCurrency, "cpaInAdvertiserCurrency");
            this.cpaInAdvertiserCurrency = cpaInAdvertiserCurrency;
            return this;
        }

        public Builder returnOnAdSpendPercent(double returnOnAdSpendPercent) {
            Utils.checkNotNull(returnOnAdSpendPercent, "returnOnAdSpendPercent");
            this.returnOnAdSpendPercent = JsonNullable.of(returnOnAdSpendPercent);
            return this;
        }

        public Builder returnOnAdSpendPercent(JsonNullable<Double> returnOnAdSpendPercent) {
            Utils.checkNotNull(returnOnAdSpendPercent, "returnOnAdSpendPercent");
            this.returnOnAdSpendPercent = returnOnAdSpendPercent;
            return this;
        }

        public Builder vcrInPercent(double vcrInPercent) {
            Utils.checkNotNull(vcrInPercent, "vcrInPercent");
            this.vcrInPercent = JsonNullable.of(vcrInPercent);
            return this;
        }

        public Builder vcrInPercent(JsonNullable<Double> vcrInPercent) {
            Utils.checkNotNull(vcrInPercent, "vcrInPercent");
            this.vcrInPercent = vcrInPercent;
            return this;
        }

        public Builder viewabilityInPercent(double viewabilityInPercent) {
            Utils.checkNotNull(viewabilityInPercent, "viewabilityInPercent");
            this.viewabilityInPercent = JsonNullable.of(viewabilityInPercent);
            return this;
        }

        public Builder viewabilityInPercent(JsonNullable<Double> viewabilityInPercent) {
            Utils.checkNotNull(viewabilityInPercent, "viewabilityInPercent");
            this.viewabilityInPercent = viewabilityInPercent;
            return this;
        }

        public Builder vcpmInAdvertiserCurrency(double vcpmInAdvertiserCurrency) {
            Utils.checkNotNull(vcpmInAdvertiserCurrency, "vcpmInAdvertiserCurrency");
            this.vcpmInAdvertiserCurrency = JsonNullable.of(vcpmInAdvertiserCurrency);
            return this;
        }

        public Builder vcpmInAdvertiserCurrency(JsonNullable<Double> vcpmInAdvertiserCurrency) {
            Utils.checkNotNull(vcpmInAdvertiserCurrency, "vcpmInAdvertiserCurrency");
            this.vcpmInAdvertiserCurrency = vcpmInAdvertiserCurrency;
            return this;
        }

        public Builder cpcvInAdvertiserCurrency(double cpcvInAdvertiserCurrency) {
            Utils.checkNotNull(cpcvInAdvertiserCurrency, "cpcvInAdvertiserCurrency");
            this.cpcvInAdvertiserCurrency = JsonNullable.of(cpcvInAdvertiserCurrency);
            return this;
        }

        public Builder cpcvInAdvertiserCurrency(JsonNullable<Double> cpcvInAdvertiserCurrency) {
            Utils.checkNotNull(cpcvInAdvertiserCurrency, "cpcvInAdvertiserCurrency");
            this.cpcvInAdvertiserCurrency = cpcvInAdvertiserCurrency;
            return this;
        }

        public Builder miaozhenOTPInPercent(double miaozhenOTPInPercent) {
            Utils.checkNotNull(miaozhenOTPInPercent, "miaozhenOTPInPercent");
            this.miaozhenOTPInPercent = JsonNullable.of(miaozhenOTPInPercent);
            return this;
        }

        public Builder miaozhenOTPInPercent(JsonNullable<Double> miaozhenOTPInPercent) {
            Utils.checkNotNull(miaozhenOTPInPercent, "miaozhenOTPInPercent");
            this.miaozhenOTPInPercent = miaozhenOTPInPercent;
            return this;
        }
        
        public AdGroupROIGoal build() {
            return new AdGroupROIGoal(
                maximizeReach,
                maximizeLtvIncrementalReach,
                cpcInAdvertiserCurrency,
                ctrInPercent,
                nielsenOTPInPercent,
                cpaInAdvertiserCurrency,
                returnOnAdSpendPercent,
                vcrInPercent,
                viewabilityInPercent,
                vcpmInAdvertiserCurrency,
                cpcvInAdvertiserCurrency,
                miaozhenOTPInPercent);
        }
    }
}
