/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;


public class AdGroupWorkflowInventoryTargetingInput {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dealGroupIdsToInclude")
    private JsonNullable<? extends List<String>> dealGroupIdsToInclude;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dealGroupIdsToExclude")
    private JsonNullable<? extends List<String>> dealGroupIdsToExclude;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dealIdsToExclude")
    private JsonNullable<? extends List<Long>> dealIdsToExclude;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dealIdsToInclude")
    private JsonNullable<? extends List<Long>> dealIdsToInclude;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("includeDefaultOnDeals")
    private JsonNullable<Boolean> includeDefaultOnDeals;

    @JsonCreator
    public AdGroupWorkflowInventoryTargetingInput(
            @JsonProperty("dealGroupIdsToInclude") JsonNullable<? extends List<String>> dealGroupIdsToInclude,
            @JsonProperty("dealGroupIdsToExclude") JsonNullable<? extends List<String>> dealGroupIdsToExclude,
            @JsonProperty("dealIdsToExclude") JsonNullable<? extends List<Long>> dealIdsToExclude,
            @JsonProperty("dealIdsToInclude") JsonNullable<? extends List<Long>> dealIdsToInclude,
            @JsonProperty("includeDefaultOnDeals") JsonNullable<Boolean> includeDefaultOnDeals) {
        Utils.checkNotNull(dealGroupIdsToInclude, "dealGroupIdsToInclude");
        Utils.checkNotNull(dealGroupIdsToExclude, "dealGroupIdsToExclude");
        Utils.checkNotNull(dealIdsToExclude, "dealIdsToExclude");
        Utils.checkNotNull(dealIdsToInclude, "dealIdsToInclude");
        Utils.checkNotNull(includeDefaultOnDeals, "includeDefaultOnDeals");
        this.dealGroupIdsToInclude = dealGroupIdsToInclude;
        this.dealGroupIdsToExclude = dealGroupIdsToExclude;
        this.dealIdsToExclude = dealIdsToExclude;
        this.dealIdsToInclude = dealIdsToInclude;
        this.includeDefaultOnDeals = includeDefaultOnDeals;
    }
    
    public AdGroupWorkflowInventoryTargetingInput() {
        this(JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined(), JsonNullable.undefined());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<List<String>> dealGroupIdsToInclude() {
        return (JsonNullable<List<String>>) dealGroupIdsToInclude;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<List<String>> dealGroupIdsToExclude() {
        return (JsonNullable<List<String>>) dealGroupIdsToExclude;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<List<Long>> dealIdsToExclude() {
        return (JsonNullable<List<Long>>) dealIdsToExclude;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<List<Long>> dealIdsToInclude() {
        return (JsonNullable<List<Long>>) dealIdsToInclude;
    }

    @JsonIgnore
    public JsonNullable<Boolean> includeDefaultOnDeals() {
        return includeDefaultOnDeals;
    }

    public static Builder builder() {
        return new Builder();
    }


    public AdGroupWorkflowInventoryTargetingInput withDealGroupIdsToInclude(List<String> dealGroupIdsToInclude) {
        Utils.checkNotNull(dealGroupIdsToInclude, "dealGroupIdsToInclude");
        this.dealGroupIdsToInclude = JsonNullable.of(dealGroupIdsToInclude);
        return this;
    }

    public AdGroupWorkflowInventoryTargetingInput withDealGroupIdsToInclude(JsonNullable<? extends List<String>> dealGroupIdsToInclude) {
        Utils.checkNotNull(dealGroupIdsToInclude, "dealGroupIdsToInclude");
        this.dealGroupIdsToInclude = dealGroupIdsToInclude;
        return this;
    }

    public AdGroupWorkflowInventoryTargetingInput withDealGroupIdsToExclude(List<String> dealGroupIdsToExclude) {
        Utils.checkNotNull(dealGroupIdsToExclude, "dealGroupIdsToExclude");
        this.dealGroupIdsToExclude = JsonNullable.of(dealGroupIdsToExclude);
        return this;
    }

    public AdGroupWorkflowInventoryTargetingInput withDealGroupIdsToExclude(JsonNullable<? extends List<String>> dealGroupIdsToExclude) {
        Utils.checkNotNull(dealGroupIdsToExclude, "dealGroupIdsToExclude");
        this.dealGroupIdsToExclude = dealGroupIdsToExclude;
        return this;
    }

    public AdGroupWorkflowInventoryTargetingInput withDealIdsToExclude(List<Long> dealIdsToExclude) {
        Utils.checkNotNull(dealIdsToExclude, "dealIdsToExclude");
        this.dealIdsToExclude = JsonNullable.of(dealIdsToExclude);
        return this;
    }

    public AdGroupWorkflowInventoryTargetingInput withDealIdsToExclude(JsonNullable<? extends List<Long>> dealIdsToExclude) {
        Utils.checkNotNull(dealIdsToExclude, "dealIdsToExclude");
        this.dealIdsToExclude = dealIdsToExclude;
        return this;
    }

    public AdGroupWorkflowInventoryTargetingInput withDealIdsToInclude(List<Long> dealIdsToInclude) {
        Utils.checkNotNull(dealIdsToInclude, "dealIdsToInclude");
        this.dealIdsToInclude = JsonNullable.of(dealIdsToInclude);
        return this;
    }

    public AdGroupWorkflowInventoryTargetingInput withDealIdsToInclude(JsonNullable<? extends List<Long>> dealIdsToInclude) {
        Utils.checkNotNull(dealIdsToInclude, "dealIdsToInclude");
        this.dealIdsToInclude = dealIdsToInclude;
        return this;
    }

    public AdGroupWorkflowInventoryTargetingInput withIncludeDefaultOnDeals(boolean includeDefaultOnDeals) {
        Utils.checkNotNull(includeDefaultOnDeals, "includeDefaultOnDeals");
        this.includeDefaultOnDeals = JsonNullable.of(includeDefaultOnDeals);
        return this;
    }

    public AdGroupWorkflowInventoryTargetingInput withIncludeDefaultOnDeals(JsonNullable<Boolean> includeDefaultOnDeals) {
        Utils.checkNotNull(includeDefaultOnDeals, "includeDefaultOnDeals");
        this.includeDefaultOnDeals = includeDefaultOnDeals;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AdGroupWorkflowInventoryTargetingInput other = (AdGroupWorkflowInventoryTargetingInput) o;
        return 
            Utils.enhancedDeepEquals(this.dealGroupIdsToInclude, other.dealGroupIdsToInclude) &&
            Utils.enhancedDeepEquals(this.dealGroupIdsToExclude, other.dealGroupIdsToExclude) &&
            Utils.enhancedDeepEquals(this.dealIdsToExclude, other.dealIdsToExclude) &&
            Utils.enhancedDeepEquals(this.dealIdsToInclude, other.dealIdsToInclude) &&
            Utils.enhancedDeepEquals(this.includeDefaultOnDeals, other.includeDefaultOnDeals);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            dealGroupIdsToInclude, dealGroupIdsToExclude, dealIdsToExclude,
            dealIdsToInclude, includeDefaultOnDeals);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AdGroupWorkflowInventoryTargetingInput.class,
                "dealGroupIdsToInclude", dealGroupIdsToInclude,
                "dealGroupIdsToExclude", dealGroupIdsToExclude,
                "dealIdsToExclude", dealIdsToExclude,
                "dealIdsToInclude", dealIdsToInclude,
                "includeDefaultOnDeals", includeDefaultOnDeals);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private JsonNullable<? extends List<String>> dealGroupIdsToInclude = JsonNullable.undefined();

        private JsonNullable<? extends List<String>> dealGroupIdsToExclude = JsonNullable.undefined();

        private JsonNullable<? extends List<Long>> dealIdsToExclude = JsonNullable.undefined();

        private JsonNullable<? extends List<Long>> dealIdsToInclude = JsonNullable.undefined();

        private JsonNullable<Boolean> includeDefaultOnDeals = JsonNullable.undefined();

        private Builder() {
          // force use of static builder() method
        }


        public Builder dealGroupIdsToInclude(List<String> dealGroupIdsToInclude) {
            Utils.checkNotNull(dealGroupIdsToInclude, "dealGroupIdsToInclude");
            this.dealGroupIdsToInclude = JsonNullable.of(dealGroupIdsToInclude);
            return this;
        }

        public Builder dealGroupIdsToInclude(JsonNullable<? extends List<String>> dealGroupIdsToInclude) {
            Utils.checkNotNull(dealGroupIdsToInclude, "dealGroupIdsToInclude");
            this.dealGroupIdsToInclude = dealGroupIdsToInclude;
            return this;
        }


        public Builder dealGroupIdsToExclude(List<String> dealGroupIdsToExclude) {
            Utils.checkNotNull(dealGroupIdsToExclude, "dealGroupIdsToExclude");
            this.dealGroupIdsToExclude = JsonNullable.of(dealGroupIdsToExclude);
            return this;
        }

        public Builder dealGroupIdsToExclude(JsonNullable<? extends List<String>> dealGroupIdsToExclude) {
            Utils.checkNotNull(dealGroupIdsToExclude, "dealGroupIdsToExclude");
            this.dealGroupIdsToExclude = dealGroupIdsToExclude;
            return this;
        }


        public Builder dealIdsToExclude(List<Long> dealIdsToExclude) {
            Utils.checkNotNull(dealIdsToExclude, "dealIdsToExclude");
            this.dealIdsToExclude = JsonNullable.of(dealIdsToExclude);
            return this;
        }

        public Builder dealIdsToExclude(JsonNullable<? extends List<Long>> dealIdsToExclude) {
            Utils.checkNotNull(dealIdsToExclude, "dealIdsToExclude");
            this.dealIdsToExclude = dealIdsToExclude;
            return this;
        }


        public Builder dealIdsToInclude(List<Long> dealIdsToInclude) {
            Utils.checkNotNull(dealIdsToInclude, "dealIdsToInclude");
            this.dealIdsToInclude = JsonNullable.of(dealIdsToInclude);
            return this;
        }

        public Builder dealIdsToInclude(JsonNullable<? extends List<Long>> dealIdsToInclude) {
            Utils.checkNotNull(dealIdsToInclude, "dealIdsToInclude");
            this.dealIdsToInclude = dealIdsToInclude;
            return this;
        }


        public Builder includeDefaultOnDeals(boolean includeDefaultOnDeals) {
            Utils.checkNotNull(includeDefaultOnDeals, "includeDefaultOnDeals");
            this.includeDefaultOnDeals = JsonNullable.of(includeDefaultOnDeals);
            return this;
        }

        public Builder includeDefaultOnDeals(JsonNullable<Boolean> includeDefaultOnDeals) {
            Utils.checkNotNull(includeDefaultOnDeals, "includeDefaultOnDeals");
            this.includeDefaultOnDeals = includeDefaultOnDeals;
            return this;
        }

        public AdGroupWorkflowInventoryTargetingInput build() {

            return new AdGroupWorkflowInventoryTargetingInput(
                dealGroupIdsToInclude, dealGroupIdsToExclude, dealIdsToExclude,
                dealIdsToInclude, includeDefaultOnDeals);
        }

    }
}
