/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

public class AdGroupCreateWorkflowInputWithValidation {

    @JsonProperty("primaryInput")
    private AdGroupCreateWorkflowPrimaryInput primaryInput;

    @JsonInclude(Include.ALWAYS)
    @JsonProperty("campaignId")
    private Optional<String> campaignId;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("advancedInput")
    private Optional<? extends AdGroupWorkflowAdvancedInput> advancedInput;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("validateInputOnly")
    private JsonNullable<Boolean> validateInputOnly;

    @JsonCreator
    public AdGroupCreateWorkflowInputWithValidation(
            @JsonProperty("primaryInput") AdGroupCreateWorkflowPrimaryInput primaryInput,
            @JsonProperty("campaignId") Optional<String> campaignId,
            @JsonProperty("advancedInput") Optional<? extends AdGroupWorkflowAdvancedInput> advancedInput,
            @JsonProperty("validateInputOnly") JsonNullable<Boolean> validateInputOnly) {
        Utils.checkNotNull(primaryInput, "primaryInput");
        Utils.checkNotNull(campaignId, "campaignId");
        Utils.checkNotNull(advancedInput, "advancedInput");
        Utils.checkNotNull(validateInputOnly, "validateInputOnly");
        this.primaryInput = primaryInput;
        this.campaignId = campaignId;
        this.advancedInput = advancedInput;
        this.validateInputOnly = validateInputOnly;
    }
    
    public AdGroupCreateWorkflowInputWithValidation(
            AdGroupCreateWorkflowPrimaryInput primaryInput) {
        this(primaryInput, Optional.empty(), Optional.empty(), JsonNullable.undefined());
    }

    @JsonIgnore
    public AdGroupCreateWorkflowPrimaryInput primaryInput() {
        return primaryInput;
    }

    @JsonIgnore
    public Optional<String> campaignId() {
        return campaignId;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<AdGroupWorkflowAdvancedInput> advancedInput() {
        return (Optional<AdGroupWorkflowAdvancedInput>) advancedInput;
    }

    @JsonIgnore
    public JsonNullable<Boolean> validateInputOnly() {
        return validateInputOnly;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public AdGroupCreateWorkflowInputWithValidation withPrimaryInput(AdGroupCreateWorkflowPrimaryInput primaryInput) {
        Utils.checkNotNull(primaryInput, "primaryInput");
        this.primaryInput = primaryInput;
        return this;
    }

    public AdGroupCreateWorkflowInputWithValidation withCampaignId(String campaignId) {
        Utils.checkNotNull(campaignId, "campaignId");
        this.campaignId = Optional.ofNullable(campaignId);
        return this;
    }

    public AdGroupCreateWorkflowInputWithValidation withCampaignId(Optional<String> campaignId) {
        Utils.checkNotNull(campaignId, "campaignId");
        this.campaignId = campaignId;
        return this;
    }

    public AdGroupCreateWorkflowInputWithValidation withAdvancedInput(AdGroupWorkflowAdvancedInput advancedInput) {
        Utils.checkNotNull(advancedInput, "advancedInput");
        this.advancedInput = Optional.ofNullable(advancedInput);
        return this;
    }

    public AdGroupCreateWorkflowInputWithValidation withAdvancedInput(Optional<? extends AdGroupWorkflowAdvancedInput> advancedInput) {
        Utils.checkNotNull(advancedInput, "advancedInput");
        this.advancedInput = advancedInput;
        return this;
    }

    public AdGroupCreateWorkflowInputWithValidation withValidateInputOnly(boolean validateInputOnly) {
        Utils.checkNotNull(validateInputOnly, "validateInputOnly");
        this.validateInputOnly = JsonNullable.of(validateInputOnly);
        return this;
    }

    public AdGroupCreateWorkflowInputWithValidation withValidateInputOnly(JsonNullable<Boolean> validateInputOnly) {
        Utils.checkNotNull(validateInputOnly, "validateInputOnly");
        this.validateInputOnly = validateInputOnly;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AdGroupCreateWorkflowInputWithValidation other = (AdGroupCreateWorkflowInputWithValidation) o;
        return 
            Objects.deepEquals(this.primaryInput, other.primaryInput) &&
            Objects.deepEquals(this.campaignId, other.campaignId) &&
            Objects.deepEquals(this.advancedInput, other.advancedInput) &&
            Objects.deepEquals(this.validateInputOnly, other.validateInputOnly);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            primaryInput,
            campaignId,
            advancedInput,
            validateInputOnly);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AdGroupCreateWorkflowInputWithValidation.class,
                "primaryInput", primaryInput,
                "campaignId", campaignId,
                "advancedInput", advancedInput,
                "validateInputOnly", validateInputOnly);
    }
    
    public final static class Builder {
 
        private AdGroupCreateWorkflowPrimaryInput primaryInput;
 
        private Optional<String> campaignId = Optional.empty();
 
        private Optional<? extends AdGroupWorkflowAdvancedInput> advancedInput = Optional.empty();
 
        private JsonNullable<Boolean> validateInputOnly = JsonNullable.undefined();
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder primaryInput(AdGroupCreateWorkflowPrimaryInput primaryInput) {
            Utils.checkNotNull(primaryInput, "primaryInput");
            this.primaryInput = primaryInput;
            return this;
        }

        public Builder campaignId(String campaignId) {
            Utils.checkNotNull(campaignId, "campaignId");
            this.campaignId = Optional.ofNullable(campaignId);
            return this;
        }

        public Builder campaignId(Optional<String> campaignId) {
            Utils.checkNotNull(campaignId, "campaignId");
            this.campaignId = campaignId;
            return this;
        }

        public Builder advancedInput(AdGroupWorkflowAdvancedInput advancedInput) {
            Utils.checkNotNull(advancedInput, "advancedInput");
            this.advancedInput = Optional.ofNullable(advancedInput);
            return this;
        }

        public Builder advancedInput(Optional<? extends AdGroupWorkflowAdvancedInput> advancedInput) {
            Utils.checkNotNull(advancedInput, "advancedInput");
            this.advancedInput = advancedInput;
            return this;
        }

        public Builder validateInputOnly(boolean validateInputOnly) {
            Utils.checkNotNull(validateInputOnly, "validateInputOnly");
            this.validateInputOnly = JsonNullable.of(validateInputOnly);
            return this;
        }

        public Builder validateInputOnly(JsonNullable<Boolean> validateInputOnly) {
            Utils.checkNotNull(validateInputOnly, "validateInputOnly");
            this.validateInputOnly = validateInputOnly;
            return this;
        }
        
        public AdGroupCreateWorkflowInputWithValidation build() {
            return new AdGroupCreateWorkflowInputWithValidation(
                primaryInput,
                campaignId,
                advancedInput,
                validateInputOnly);
        }
    }
}
