/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;


public class AdGroupWorkflowNielsenTrackingAttributesInput {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("enhancedReportingOption")
    private Optional<? extends EnhancedNielsenReportingOptionsInput> enhancedReportingOption;


    @JsonProperty("gender")
    private TargetingGenderInput gender;


    @JsonProperty("startAge")
    private TargetingStartAgeInput startAge;


    @JsonProperty("endAge")
    private TargetingEndAgeInput endAge;


    @JsonInclude(Include.ALWAYS)
    @JsonProperty("countries")
    private Optional<? extends List<String>> countries;

    @JsonCreator
    public AdGroupWorkflowNielsenTrackingAttributesInput(
            @JsonProperty("enhancedReportingOption") Optional<? extends EnhancedNielsenReportingOptionsInput> enhancedReportingOption,
            @JsonProperty("gender") TargetingGenderInput gender,
            @JsonProperty("startAge") TargetingStartAgeInput startAge,
            @JsonProperty("endAge") TargetingEndAgeInput endAge,
            @JsonProperty("countries") Optional<? extends List<String>> countries) {
        Utils.checkNotNull(enhancedReportingOption, "enhancedReportingOption");
        Utils.checkNotNull(gender, "gender");
        Utils.checkNotNull(startAge, "startAge");
        Utils.checkNotNull(endAge, "endAge");
        Utils.checkNotNull(countries, "countries");
        this.enhancedReportingOption = enhancedReportingOption;
        this.gender = gender;
        this.startAge = startAge;
        this.endAge = endAge;
        this.countries = countries;
    }
    
    public AdGroupWorkflowNielsenTrackingAttributesInput(
            TargetingGenderInput gender,
            TargetingStartAgeInput startAge,
            TargetingEndAgeInput endAge) {
        this(Optional.empty(), gender, startAge,
            endAge, Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<EnhancedNielsenReportingOptionsInput> enhancedReportingOption() {
        return (Optional<EnhancedNielsenReportingOptionsInput>) enhancedReportingOption;
    }

    @JsonIgnore
    public TargetingGenderInput gender() {
        return gender;
    }

    @JsonIgnore
    public TargetingStartAgeInput startAge() {
        return startAge;
    }

    @JsonIgnore
    public TargetingEndAgeInput endAge() {
        return endAge;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<String>> countries() {
        return (Optional<List<String>>) countries;
    }

    public static Builder builder() {
        return new Builder();
    }


    public AdGroupWorkflowNielsenTrackingAttributesInput withEnhancedReportingOption(EnhancedNielsenReportingOptionsInput enhancedReportingOption) {
        Utils.checkNotNull(enhancedReportingOption, "enhancedReportingOption");
        this.enhancedReportingOption = Optional.ofNullable(enhancedReportingOption);
        return this;
    }


    public AdGroupWorkflowNielsenTrackingAttributesInput withEnhancedReportingOption(Optional<? extends EnhancedNielsenReportingOptionsInput> enhancedReportingOption) {
        Utils.checkNotNull(enhancedReportingOption, "enhancedReportingOption");
        this.enhancedReportingOption = enhancedReportingOption;
        return this;
    }

    public AdGroupWorkflowNielsenTrackingAttributesInput withGender(TargetingGenderInput gender) {
        Utils.checkNotNull(gender, "gender");
        this.gender = gender;
        return this;
    }

    public AdGroupWorkflowNielsenTrackingAttributesInput withStartAge(TargetingStartAgeInput startAge) {
        Utils.checkNotNull(startAge, "startAge");
        this.startAge = startAge;
        return this;
    }

    public AdGroupWorkflowNielsenTrackingAttributesInput withEndAge(TargetingEndAgeInput endAge) {
        Utils.checkNotNull(endAge, "endAge");
        this.endAge = endAge;
        return this;
    }

    public AdGroupWorkflowNielsenTrackingAttributesInput withCountries(List<String> countries) {
        Utils.checkNotNull(countries, "countries");
        this.countries = Optional.ofNullable(countries);
        return this;
    }


    public AdGroupWorkflowNielsenTrackingAttributesInput withCountries(Optional<? extends List<String>> countries) {
        Utils.checkNotNull(countries, "countries");
        this.countries = countries;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AdGroupWorkflowNielsenTrackingAttributesInput other = (AdGroupWorkflowNielsenTrackingAttributesInput) o;
        return 
            Utils.enhancedDeepEquals(this.enhancedReportingOption, other.enhancedReportingOption) &&
            Utils.enhancedDeepEquals(this.gender, other.gender) &&
            Utils.enhancedDeepEquals(this.startAge, other.startAge) &&
            Utils.enhancedDeepEquals(this.endAge, other.endAge) &&
            Utils.enhancedDeepEquals(this.countries, other.countries);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            enhancedReportingOption, gender, startAge,
            endAge, countries);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AdGroupWorkflowNielsenTrackingAttributesInput.class,
                "enhancedReportingOption", enhancedReportingOption,
                "gender", gender,
                "startAge", startAge,
                "endAge", endAge,
                "countries", countries);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends EnhancedNielsenReportingOptionsInput> enhancedReportingOption = Optional.empty();

        private TargetingGenderInput gender;

        private TargetingStartAgeInput startAge;

        private TargetingEndAgeInput endAge;

        private Optional<? extends List<String>> countries = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder enhancedReportingOption(EnhancedNielsenReportingOptionsInput enhancedReportingOption) {
            Utils.checkNotNull(enhancedReportingOption, "enhancedReportingOption");
            this.enhancedReportingOption = Optional.ofNullable(enhancedReportingOption);
            return this;
        }

        public Builder enhancedReportingOption(Optional<? extends EnhancedNielsenReportingOptionsInput> enhancedReportingOption) {
            Utils.checkNotNull(enhancedReportingOption, "enhancedReportingOption");
            this.enhancedReportingOption = enhancedReportingOption;
            return this;
        }


        public Builder gender(TargetingGenderInput gender) {
            Utils.checkNotNull(gender, "gender");
            this.gender = gender;
            return this;
        }


        public Builder startAge(TargetingStartAgeInput startAge) {
            Utils.checkNotNull(startAge, "startAge");
            this.startAge = startAge;
            return this;
        }


        public Builder endAge(TargetingEndAgeInput endAge) {
            Utils.checkNotNull(endAge, "endAge");
            this.endAge = endAge;
            return this;
        }


        public Builder countries(List<String> countries) {
            Utils.checkNotNull(countries, "countries");
            this.countries = Optional.ofNullable(countries);
            return this;
        }

        public Builder countries(Optional<? extends List<String>> countries) {
            Utils.checkNotNull(countries, "countries");
            this.countries = countries;
            return this;
        }

        public AdGroupWorkflowNielsenTrackingAttributesInput build() {

            return new AdGroupWorkflowNielsenTrackingAttributesInput(
                enhancedReportingOption, gender, startAge,
                endAge, countries);
        }

    }
}
