/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapitools.jackson.nullable.JsonNullable;

public class AdGroupKoaOptimizationSettingsInput {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("areFutureKoaFeaturesEnabled")
    private JsonNullable<Boolean> areFutureKoaFeaturesEnabled;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("predictiveClearingEnabled")
    private JsonNullable<Boolean> predictiveClearingEnabled;

    @JsonCreator
    public AdGroupKoaOptimizationSettingsInput(
            @JsonProperty("areFutureKoaFeaturesEnabled") JsonNullable<Boolean> areFutureKoaFeaturesEnabled,
            @JsonProperty("predictiveClearingEnabled") JsonNullable<Boolean> predictiveClearingEnabled) {
        Utils.checkNotNull(areFutureKoaFeaturesEnabled, "areFutureKoaFeaturesEnabled");
        Utils.checkNotNull(predictiveClearingEnabled, "predictiveClearingEnabled");
        this.areFutureKoaFeaturesEnabled = areFutureKoaFeaturesEnabled;
        this.predictiveClearingEnabled = predictiveClearingEnabled;
    }
    
    public AdGroupKoaOptimizationSettingsInput() {
        this(JsonNullable.undefined(), JsonNullable.undefined());
    }

    @JsonIgnore
    public JsonNullable<Boolean> areFutureKoaFeaturesEnabled() {
        return areFutureKoaFeaturesEnabled;
    }

    @JsonIgnore
    public JsonNullable<Boolean> predictiveClearingEnabled() {
        return predictiveClearingEnabled;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public AdGroupKoaOptimizationSettingsInput withAreFutureKoaFeaturesEnabled(boolean areFutureKoaFeaturesEnabled) {
        Utils.checkNotNull(areFutureKoaFeaturesEnabled, "areFutureKoaFeaturesEnabled");
        this.areFutureKoaFeaturesEnabled = JsonNullable.of(areFutureKoaFeaturesEnabled);
        return this;
    }

    public AdGroupKoaOptimizationSettingsInput withAreFutureKoaFeaturesEnabled(JsonNullable<Boolean> areFutureKoaFeaturesEnabled) {
        Utils.checkNotNull(areFutureKoaFeaturesEnabled, "areFutureKoaFeaturesEnabled");
        this.areFutureKoaFeaturesEnabled = areFutureKoaFeaturesEnabled;
        return this;
    }

    public AdGroupKoaOptimizationSettingsInput withPredictiveClearingEnabled(boolean predictiveClearingEnabled) {
        Utils.checkNotNull(predictiveClearingEnabled, "predictiveClearingEnabled");
        this.predictiveClearingEnabled = JsonNullable.of(predictiveClearingEnabled);
        return this;
    }

    public AdGroupKoaOptimizationSettingsInput withPredictiveClearingEnabled(JsonNullable<Boolean> predictiveClearingEnabled) {
        Utils.checkNotNull(predictiveClearingEnabled, "predictiveClearingEnabled");
        this.predictiveClearingEnabled = predictiveClearingEnabled;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AdGroupKoaOptimizationSettingsInput other = (AdGroupKoaOptimizationSettingsInput) o;
        return 
            Objects.deepEquals(this.areFutureKoaFeaturesEnabled, other.areFutureKoaFeaturesEnabled) &&
            Objects.deepEquals(this.predictiveClearingEnabled, other.predictiveClearingEnabled);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            areFutureKoaFeaturesEnabled,
            predictiveClearingEnabled);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AdGroupKoaOptimizationSettingsInput.class,
                "areFutureKoaFeaturesEnabled", areFutureKoaFeaturesEnabled,
                "predictiveClearingEnabled", predictiveClearingEnabled);
    }
    
    public final static class Builder {
 
        private JsonNullable<Boolean> areFutureKoaFeaturesEnabled = JsonNullable.undefined();
 
        private JsonNullable<Boolean> predictiveClearingEnabled = JsonNullable.undefined();
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder areFutureKoaFeaturesEnabled(boolean areFutureKoaFeaturesEnabled) {
            Utils.checkNotNull(areFutureKoaFeaturesEnabled, "areFutureKoaFeaturesEnabled");
            this.areFutureKoaFeaturesEnabled = JsonNullable.of(areFutureKoaFeaturesEnabled);
            return this;
        }

        public Builder areFutureKoaFeaturesEnabled(JsonNullable<Boolean> areFutureKoaFeaturesEnabled) {
            Utils.checkNotNull(areFutureKoaFeaturesEnabled, "areFutureKoaFeaturesEnabled");
            this.areFutureKoaFeaturesEnabled = areFutureKoaFeaturesEnabled;
            return this;
        }

        public Builder predictiveClearingEnabled(boolean predictiveClearingEnabled) {
            Utils.checkNotNull(predictiveClearingEnabled, "predictiveClearingEnabled");
            this.predictiveClearingEnabled = JsonNullable.of(predictiveClearingEnabled);
            return this;
        }

        public Builder predictiveClearingEnabled(JsonNullable<Boolean> predictiveClearingEnabled) {
            Utils.checkNotNull(predictiveClearingEnabled, "predictiveClearingEnabled");
            this.predictiveClearingEnabled = predictiveClearingEnabled;
            return this;
        }
        
        public AdGroupKoaOptimizationSettingsInput build() {
            return new AdGroupKoaOptimizationSettingsInput(
                areFutureKoaFeaturesEnabled,
                predictiveClearingEnabled);
        }
    }
}
