/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */


package com.thetradedesk.workflows.models.components;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
public enum CampaignChannel {
    NONE("None"),
    DISPLAY("Display"),
    AUDIO("Audio"),
    VIDEO("Video"),
    TV("TV"),
    NATIVE_VIDEO("NativeVideo"),
    NATIVE_DISPLAY("NativeDisplay"),
    DOOH("DOOH");

    @JsonValue
    private final String value;

    private CampaignChannel(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<CampaignChannel> fromValue(String value) {
        for (CampaignChannel o: CampaignChannel.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
