/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class CampaignWorkflowCampaignConversionReportingColumnInput {

    @JsonProperty("trackingTagId")
    private String trackingTagId;


    @JsonProperty("includeInCustomCPA")
    private boolean includeInCustomCPA;


    @JsonProperty("reportingColumnId")
    private int reportingColumnId;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ROASConfig")
    private Optional<? extends CustomROASConfig> roasConfig;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("weight")
    private JsonNullable<Double> weight;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("crossDeviceAttributionModelId")
    private JsonNullable<String> crossDeviceAttributionModelId;

    @JsonCreator
    public CampaignWorkflowCampaignConversionReportingColumnInput(
            @JsonProperty("trackingTagId") String trackingTagId,
            @JsonProperty("includeInCustomCPA") boolean includeInCustomCPA,
            @JsonProperty("reportingColumnId") int reportingColumnId,
            @JsonProperty("ROASConfig") Optional<? extends CustomROASConfig> roasConfig,
            @JsonProperty("weight") JsonNullable<Double> weight,
            @JsonProperty("crossDeviceAttributionModelId") JsonNullable<String> crossDeviceAttributionModelId) {
        Utils.checkNotNull(trackingTagId, "trackingTagId");
        Utils.checkNotNull(includeInCustomCPA, "includeInCustomCPA");
        Utils.checkNotNull(reportingColumnId, "reportingColumnId");
        Utils.checkNotNull(roasConfig, "roasConfig");
        Utils.checkNotNull(weight, "weight");
        Utils.checkNotNull(crossDeviceAttributionModelId, "crossDeviceAttributionModelId");
        this.trackingTagId = trackingTagId;
        this.includeInCustomCPA = includeInCustomCPA;
        this.reportingColumnId = reportingColumnId;
        this.roasConfig = roasConfig;
        this.weight = weight;
        this.crossDeviceAttributionModelId = crossDeviceAttributionModelId;
    }
    
    public CampaignWorkflowCampaignConversionReportingColumnInput(
            String trackingTagId,
            boolean includeInCustomCPA,
            int reportingColumnId) {
        this(trackingTagId, includeInCustomCPA, reportingColumnId,
            Optional.empty(), JsonNullable.undefined(), JsonNullable.undefined());
    }

    @JsonIgnore
    public String trackingTagId() {
        return trackingTagId;
    }

    @JsonIgnore
    public boolean includeInCustomCPA() {
        return includeInCustomCPA;
    }

    @JsonIgnore
    public int reportingColumnId() {
        return reportingColumnId;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<CustomROASConfig> roasConfig() {
        return (Optional<CustomROASConfig>) roasConfig;
    }

    @JsonIgnore
    public JsonNullable<Double> weight() {
        return weight;
    }

    @JsonIgnore
    public JsonNullable<String> crossDeviceAttributionModelId() {
        return crossDeviceAttributionModelId;
    }

    public static Builder builder() {
        return new Builder();
    }


    public CampaignWorkflowCampaignConversionReportingColumnInput withTrackingTagId(String trackingTagId) {
        Utils.checkNotNull(trackingTagId, "trackingTagId");
        this.trackingTagId = trackingTagId;
        return this;
    }

    public CampaignWorkflowCampaignConversionReportingColumnInput withIncludeInCustomCPA(boolean includeInCustomCPA) {
        Utils.checkNotNull(includeInCustomCPA, "includeInCustomCPA");
        this.includeInCustomCPA = includeInCustomCPA;
        return this;
    }

    public CampaignWorkflowCampaignConversionReportingColumnInput withReportingColumnId(int reportingColumnId) {
        Utils.checkNotNull(reportingColumnId, "reportingColumnId");
        this.reportingColumnId = reportingColumnId;
        return this;
    }

    public CampaignWorkflowCampaignConversionReportingColumnInput withROASConfig(CustomROASConfig roasConfig) {
        Utils.checkNotNull(roasConfig, "roasConfig");
        this.roasConfig = Optional.ofNullable(roasConfig);
        return this;
    }


    public CampaignWorkflowCampaignConversionReportingColumnInput withROASConfig(Optional<? extends CustomROASConfig> roasConfig) {
        Utils.checkNotNull(roasConfig, "roasConfig");
        this.roasConfig = roasConfig;
        return this;
    }

    public CampaignWorkflowCampaignConversionReportingColumnInput withWeight(double weight) {
        Utils.checkNotNull(weight, "weight");
        this.weight = JsonNullable.of(weight);
        return this;
    }

    public CampaignWorkflowCampaignConversionReportingColumnInput withWeight(JsonNullable<Double> weight) {
        Utils.checkNotNull(weight, "weight");
        this.weight = weight;
        return this;
    }

    public CampaignWorkflowCampaignConversionReportingColumnInput withCrossDeviceAttributionModelId(String crossDeviceAttributionModelId) {
        Utils.checkNotNull(crossDeviceAttributionModelId, "crossDeviceAttributionModelId");
        this.crossDeviceAttributionModelId = JsonNullable.of(crossDeviceAttributionModelId);
        return this;
    }

    public CampaignWorkflowCampaignConversionReportingColumnInput withCrossDeviceAttributionModelId(JsonNullable<String> crossDeviceAttributionModelId) {
        Utils.checkNotNull(crossDeviceAttributionModelId, "crossDeviceAttributionModelId");
        this.crossDeviceAttributionModelId = crossDeviceAttributionModelId;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CampaignWorkflowCampaignConversionReportingColumnInput other = (CampaignWorkflowCampaignConversionReportingColumnInput) o;
        return 
            Utils.enhancedDeepEquals(this.trackingTagId, other.trackingTagId) &&
            Utils.enhancedDeepEquals(this.includeInCustomCPA, other.includeInCustomCPA) &&
            Utils.enhancedDeepEquals(this.reportingColumnId, other.reportingColumnId) &&
            Utils.enhancedDeepEquals(this.roasConfig, other.roasConfig) &&
            Utils.enhancedDeepEquals(this.weight, other.weight) &&
            Utils.enhancedDeepEquals(this.crossDeviceAttributionModelId, other.crossDeviceAttributionModelId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            trackingTagId, includeInCustomCPA, reportingColumnId,
            roasConfig, weight, crossDeviceAttributionModelId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CampaignWorkflowCampaignConversionReportingColumnInput.class,
                "trackingTagId", trackingTagId,
                "includeInCustomCPA", includeInCustomCPA,
                "reportingColumnId", reportingColumnId,
                "roasConfig", roasConfig,
                "weight", weight,
                "crossDeviceAttributionModelId", crossDeviceAttributionModelId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String trackingTagId;

        private Boolean includeInCustomCPA;

        private Integer reportingColumnId;

        private Optional<? extends CustomROASConfig> roasConfig = Optional.empty();

        private JsonNullable<Double> weight = JsonNullable.undefined();

        private JsonNullable<String> crossDeviceAttributionModelId = JsonNullable.undefined();

        private Builder() {
          // force use of static builder() method
        }


        public Builder trackingTagId(String trackingTagId) {
            Utils.checkNotNull(trackingTagId, "trackingTagId");
            this.trackingTagId = trackingTagId;
            return this;
        }


        public Builder includeInCustomCPA(boolean includeInCustomCPA) {
            Utils.checkNotNull(includeInCustomCPA, "includeInCustomCPA");
            this.includeInCustomCPA = includeInCustomCPA;
            return this;
        }


        public Builder reportingColumnId(int reportingColumnId) {
            Utils.checkNotNull(reportingColumnId, "reportingColumnId");
            this.reportingColumnId = reportingColumnId;
            return this;
        }


        public Builder roasConfig(CustomROASConfig roasConfig) {
            Utils.checkNotNull(roasConfig, "roasConfig");
            this.roasConfig = Optional.ofNullable(roasConfig);
            return this;
        }

        public Builder roasConfig(Optional<? extends CustomROASConfig> roasConfig) {
            Utils.checkNotNull(roasConfig, "roasConfig");
            this.roasConfig = roasConfig;
            return this;
        }


        public Builder weight(double weight) {
            Utils.checkNotNull(weight, "weight");
            this.weight = JsonNullable.of(weight);
            return this;
        }

        public Builder weight(JsonNullable<Double> weight) {
            Utils.checkNotNull(weight, "weight");
            this.weight = weight;
            return this;
        }


        public Builder crossDeviceAttributionModelId(String crossDeviceAttributionModelId) {
            Utils.checkNotNull(crossDeviceAttributionModelId, "crossDeviceAttributionModelId");
            this.crossDeviceAttributionModelId = JsonNullable.of(crossDeviceAttributionModelId);
            return this;
        }

        public Builder crossDeviceAttributionModelId(JsonNullable<String> crossDeviceAttributionModelId) {
            Utils.checkNotNull(crossDeviceAttributionModelId, "crossDeviceAttributionModelId");
            this.crossDeviceAttributionModelId = crossDeviceAttributionModelId;
            return this;
        }

        public CampaignWorkflowCampaignConversionReportingColumnInput build() {

            return new CampaignWorkflowCampaignConversionReportingColumnInput(
                trackingTagId, includeInCustomCPA, reportingColumnId,
                roasConfig, weight, crossDeviceAttributionModelId);
        }

    }
}
