/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

public class CampaignBulkCreateWorkflowInputWithValidation {

    @JsonInclude(Include.ALWAYS)
    @JsonProperty("input")
    private Optional<? extends List<CampaignCreateWorkflowInput>> input;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("validateInputOnly")
    private JsonNullable<Boolean> validateInputOnly;

    @JsonCreator
    public CampaignBulkCreateWorkflowInputWithValidation(
            @JsonProperty("input") Optional<? extends List<CampaignCreateWorkflowInput>> input,
            @JsonProperty("validateInputOnly") JsonNullable<Boolean> validateInputOnly) {
        Utils.checkNotNull(input, "input");
        Utils.checkNotNull(validateInputOnly, "validateInputOnly");
        this.input = input;
        this.validateInputOnly = validateInputOnly;
    }
    
    public CampaignBulkCreateWorkflowInputWithValidation() {
        this(Optional.empty(), JsonNullable.undefined());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<CampaignCreateWorkflowInput>> input() {
        return (Optional<List<CampaignCreateWorkflowInput>>) input;
    }

    @JsonIgnore
    public JsonNullable<Boolean> validateInputOnly() {
        return validateInputOnly;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public CampaignBulkCreateWorkflowInputWithValidation withInput(List<CampaignCreateWorkflowInput> input) {
        Utils.checkNotNull(input, "input");
        this.input = Optional.ofNullable(input);
        return this;
    }

    public CampaignBulkCreateWorkflowInputWithValidation withInput(Optional<? extends List<CampaignCreateWorkflowInput>> input) {
        Utils.checkNotNull(input, "input");
        this.input = input;
        return this;
    }

    public CampaignBulkCreateWorkflowInputWithValidation withValidateInputOnly(boolean validateInputOnly) {
        Utils.checkNotNull(validateInputOnly, "validateInputOnly");
        this.validateInputOnly = JsonNullable.of(validateInputOnly);
        return this;
    }

    public CampaignBulkCreateWorkflowInputWithValidation withValidateInputOnly(JsonNullable<Boolean> validateInputOnly) {
        Utils.checkNotNull(validateInputOnly, "validateInputOnly");
        this.validateInputOnly = validateInputOnly;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CampaignBulkCreateWorkflowInputWithValidation other = (CampaignBulkCreateWorkflowInputWithValidation) o;
        return 
            Objects.deepEquals(this.input, other.input) &&
            Objects.deepEquals(this.validateInputOnly, other.validateInputOnly);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            input,
            validateInputOnly);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CampaignBulkCreateWorkflowInputWithValidation.class,
                "input", input,
                "validateInputOnly", validateInputOnly);
    }
    
    public final static class Builder {
 
        private Optional<? extends List<CampaignCreateWorkflowInput>> input = Optional.empty();
 
        private JsonNullable<Boolean> validateInputOnly = JsonNullable.undefined();
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder input(List<CampaignCreateWorkflowInput> input) {
            Utils.checkNotNull(input, "input");
            this.input = Optional.ofNullable(input);
            return this;
        }

        public Builder input(Optional<? extends List<CampaignCreateWorkflowInput>> input) {
            Utils.checkNotNull(input, "input");
            this.input = input;
            return this;
        }

        public Builder validateInputOnly(boolean validateInputOnly) {
            Utils.checkNotNull(validateInputOnly, "validateInputOnly");
            this.validateInputOnly = JsonNullable.of(validateInputOnly);
            return this;
        }

        public Builder validateInputOnly(JsonNullable<Boolean> validateInputOnly) {
            Utils.checkNotNull(validateInputOnly, "validateInputOnly");
            this.validateInputOnly = validateInputOnly;
            return this;
        }
        
        public CampaignBulkCreateWorkflowInputWithValidation build() {
            return new CampaignBulkCreateWorkflowInputWithValidation(
                input,
                validateInputOnly);
        }
    }
}
