/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Double;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class CampaignCreatePassThroughFeesInput {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private Optional<? extends PassThroughFeeType> type;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private JsonNullable<String> description;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("amount")
    private Optional<Double> amount;

    @JsonCreator
    public CampaignCreatePassThroughFeesInput(
            @JsonProperty("type") Optional<? extends PassThroughFeeType> type,
            @JsonProperty("description") JsonNullable<String> description,
            @JsonProperty("amount") Optional<Double> amount) {
        Utils.checkNotNull(type, "type");
        Utils.checkNotNull(description, "description");
        Utils.checkNotNull(amount, "amount");
        this.type = type;
        this.description = description;
        this.amount = amount;
    }
    
    public CampaignCreatePassThroughFeesInput() {
        this(Optional.empty(), JsonNullable.undefined(), Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PassThroughFeeType> type() {
        return (Optional<PassThroughFeeType>) type;
    }

    @JsonIgnore
    public JsonNullable<String> description() {
        return description;
    }

    @JsonIgnore
    public Optional<Double> amount() {
        return amount;
    }

    public static Builder builder() {
        return new Builder();
    }


    public CampaignCreatePassThroughFeesInput withType(PassThroughFeeType type) {
        Utils.checkNotNull(type, "type");
        this.type = Optional.ofNullable(type);
        return this;
    }


    public CampaignCreatePassThroughFeesInput withType(Optional<? extends PassThroughFeeType> type) {
        Utils.checkNotNull(type, "type");
        this.type = type;
        return this;
    }

    public CampaignCreatePassThroughFeesInput withDescription(String description) {
        Utils.checkNotNull(description, "description");
        this.description = JsonNullable.of(description);
        return this;
    }

    public CampaignCreatePassThroughFeesInput withDescription(JsonNullable<String> description) {
        Utils.checkNotNull(description, "description");
        this.description = description;
        return this;
    }

    public CampaignCreatePassThroughFeesInput withAmount(double amount) {
        Utils.checkNotNull(amount, "amount");
        this.amount = Optional.ofNullable(amount);
        return this;
    }


    public CampaignCreatePassThroughFeesInput withAmount(Optional<Double> amount) {
        Utils.checkNotNull(amount, "amount");
        this.amount = amount;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CampaignCreatePassThroughFeesInput other = (CampaignCreatePassThroughFeesInput) o;
        return 
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.description, other.description) &&
            Utils.enhancedDeepEquals(this.amount, other.amount);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            type, description, amount);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CampaignCreatePassThroughFeesInput.class,
                "type", type,
                "description", description,
                "amount", amount);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends PassThroughFeeType> type = Optional.empty();

        private JsonNullable<String> description = JsonNullable.undefined();

        private Optional<Double> amount = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder type(PassThroughFeeType type) {
            Utils.checkNotNull(type, "type");
            this.type = Optional.ofNullable(type);
            return this;
        }

        public Builder type(Optional<? extends PassThroughFeeType> type) {
            Utils.checkNotNull(type, "type");
            this.type = type;
            return this;
        }


        public Builder description(String description) {
            Utils.checkNotNull(description, "description");
            this.description = JsonNullable.of(description);
            return this;
        }

        public Builder description(JsonNullable<String> description) {
            Utils.checkNotNull(description, "description");
            this.description = description;
            return this;
        }


        public Builder amount(double amount) {
            Utils.checkNotNull(amount, "amount");
            this.amount = Optional.ofNullable(amount);
            return this;
        }

        public Builder amount(Optional<Double> amount) {
            Utils.checkNotNull(amount, "amount");
            this.amount = amount;
            return this;
        }

        public CampaignCreatePassThroughFeesInput build() {

            return new CampaignCreatePassThroughFeesInput(
                type, description, amount);
        }

    }
}
