/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import org.openapitools.jackson.nullable.JsonNullable;

public class ContextualDataInput {

    /**
     * Keyphrases
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("keyphrases")
    private JsonNullable<? extends List<String>> keyphrases;

    /**
     * Urls
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("urls")
    private JsonNullable<? extends List<String>> urls;

    @JsonCreator
    public ContextualDataInput(
            @JsonProperty("keyphrases") JsonNullable<? extends List<String>> keyphrases,
            @JsonProperty("urls") JsonNullable<? extends List<String>> urls) {
        Utils.checkNotNull(keyphrases, "keyphrases");
        Utils.checkNotNull(urls, "urls");
        this.keyphrases = keyphrases;
        this.urls = urls;
    }
    
    public ContextualDataInput() {
        this(JsonNullable.undefined(), JsonNullable.undefined());
    }

    /**
     * Keyphrases
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<List<String>> keyphrases() {
        return (JsonNullable<List<String>>) keyphrases;
    }

    /**
     * Urls
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<List<String>> urls() {
        return (JsonNullable<List<String>>) urls;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Keyphrases
     */
    public ContextualDataInput withKeyphrases(List<String> keyphrases) {
        Utils.checkNotNull(keyphrases, "keyphrases");
        this.keyphrases = JsonNullable.of(keyphrases);
        return this;
    }

    /**
     * Keyphrases
     */
    public ContextualDataInput withKeyphrases(JsonNullable<? extends List<String>> keyphrases) {
        Utils.checkNotNull(keyphrases, "keyphrases");
        this.keyphrases = keyphrases;
        return this;
    }

    /**
     * Urls
     */
    public ContextualDataInput withUrls(List<String> urls) {
        Utils.checkNotNull(urls, "urls");
        this.urls = JsonNullable.of(urls);
        return this;
    }

    /**
     * Urls
     */
    public ContextualDataInput withUrls(JsonNullable<? extends List<String>> urls) {
        Utils.checkNotNull(urls, "urls");
        this.urls = urls;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ContextualDataInput other = (ContextualDataInput) o;
        return 
            Objects.deepEquals(this.keyphrases, other.keyphrases) &&
            Objects.deepEquals(this.urls, other.urls);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            keyphrases,
            urls);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ContextualDataInput.class,
                "keyphrases", keyphrases,
                "urls", urls);
    }
    
    public final static class Builder {
 
        private JsonNullable<? extends List<String>> keyphrases = JsonNullable.undefined();
 
        private JsonNullable<? extends List<String>> urls = JsonNullable.undefined();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Keyphrases
         */
        public Builder keyphrases(List<String> keyphrases) {
            Utils.checkNotNull(keyphrases, "keyphrases");
            this.keyphrases = JsonNullable.of(keyphrases);
            return this;
        }

        /**
         * Keyphrases
         */
        public Builder keyphrases(JsonNullable<? extends List<String>> keyphrases) {
            Utils.checkNotNull(keyphrases, "keyphrases");
            this.keyphrases = keyphrases;
            return this;
        }

        /**
         * Urls
         */
        public Builder urls(List<String> urls) {
            Utils.checkNotNull(urls, "urls");
            this.urls = JsonNullable.of(urls);
            return this;
        }

        /**
         * Urls
         */
        public Builder urls(JsonNullable<? extends List<String>> urls) {
            Utils.checkNotNull(urls, "urls");
            this.urls = urls;
            return this;
        }
        
        public ContextualDataInput build() {
            return new ContextualDataInput(
                keyphrases,
                urls);
        }
    }
}
