/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum EnhancedNielsenReportingOptions {
    NONE("None"),
    AUDIENCE("Audience"),
    SITE("Site");

    @JsonValue
    private final String value;

    EnhancedNielsenReportingOptions(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<EnhancedNielsenReportingOptions> fromValue(String value) {
        for (EnhancedNielsenReportingOptions o: EnhancedNielsenReportingOptions.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

