/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum IntegralViewabilityInput {
    IN_VIEW40("InView40"),
    IN_VIEW50("InView50"),
    IN_VIEW60("InView60"),
    IN_VIEW70("InView70");

    @JsonValue
    private final String value;

    IntegralViewabilityInput(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<IntegralViewabilityInput> fromValue(String value) {
        for (IntegralViewabilityInput o: IntegralViewabilityInput.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

