/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum NativeContextType {
    UNCLASSIFIED("Unclassified"),
    CONTENT("Content"),
    SOCIAL("Social"),
    PRODUCT("Product"),
    CONTENT_UNCLASSIFIED("ContentUnclassified"),
    SOCIAL_UNCLASSIFIED("SocialUnclassified"),
    PRODUCT_UNCLASSIFIED("ProductUnclassified"),
    GENERAL("General"),
    ARTICLE("Article"),
    VIDEO("Video"),
    AUDIO("Audio"),
    IMAGE("Image"),
    USER_GENERATED("UserGenerated"),
    GENERAL_SOCIAL("GeneralSocial"),
    EMAIL("Email"),
    CHAT_OR_IM("ChatOrIM"),
    SELLING_PRODUCTS("SellingProducts"),
    APPLICATION_STORE("ApplicationStore"),
    PRODUCT_REVIEW("ProductReview");

    @JsonValue
    private final String value;

    NativeContextType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<NativeContextType> fromValue(String value) {
        for (NativeContextType o: NativeContextType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

