/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class RealyticsReachSettingInput {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private Optional<Integer> id;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private JsonNullable<String> name;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("isActive")
    private Optional<Boolean> isActive;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("products")
    private JsonNullable<? extends List<IncrementalReachProductInput>> products;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("realyticsEntertainmentInput")
    private Optional<? extends RealyticsEntertainmentType> realyticsEntertainmentInput;

    @JsonCreator
    public RealyticsReachSettingInput(
            @JsonProperty("id") Optional<Integer> id,
            @JsonProperty("name") JsonNullable<String> name,
            @JsonProperty("isActive") Optional<Boolean> isActive,
            @JsonProperty("products") JsonNullable<? extends List<IncrementalReachProductInput>> products,
            @JsonProperty("realyticsEntertainmentInput") Optional<? extends RealyticsEntertainmentType> realyticsEntertainmentInput) {
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(isActive, "isActive");
        Utils.checkNotNull(products, "products");
        Utils.checkNotNull(realyticsEntertainmentInput, "realyticsEntertainmentInput");
        this.id = id;
        this.name = name;
        this.isActive = isActive;
        this.products = products;
        this.realyticsEntertainmentInput = realyticsEntertainmentInput;
    }
    
    public RealyticsReachSettingInput() {
        this(Optional.empty(), JsonNullable.undefined(), Optional.empty(),
            JsonNullable.undefined(), Optional.empty());
    }

    @JsonIgnore
    public Optional<Integer> id() {
        return id;
    }

    @JsonIgnore
    public JsonNullable<String> name() {
        return name;
    }

    @JsonIgnore
    public Optional<Boolean> isActive() {
        return isActive;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<List<IncrementalReachProductInput>> products() {
        return (JsonNullable<List<IncrementalReachProductInput>>) products;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<RealyticsEntertainmentType> realyticsEntertainmentInput() {
        return (Optional<RealyticsEntertainmentType>) realyticsEntertainmentInput;
    }

    public static Builder builder() {
        return new Builder();
    }


    public RealyticsReachSettingInput withId(int id) {
        Utils.checkNotNull(id, "id");
        this.id = Optional.ofNullable(id);
        return this;
    }


    public RealyticsReachSettingInput withId(Optional<Integer> id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public RealyticsReachSettingInput withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = JsonNullable.of(name);
        return this;
    }

    public RealyticsReachSettingInput withName(JsonNullable<String> name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    public RealyticsReachSettingInput withIsActive(boolean isActive) {
        Utils.checkNotNull(isActive, "isActive");
        this.isActive = Optional.ofNullable(isActive);
        return this;
    }


    public RealyticsReachSettingInput withIsActive(Optional<Boolean> isActive) {
        Utils.checkNotNull(isActive, "isActive");
        this.isActive = isActive;
        return this;
    }

    public RealyticsReachSettingInput withProducts(List<IncrementalReachProductInput> products) {
        Utils.checkNotNull(products, "products");
        this.products = JsonNullable.of(products);
        return this;
    }

    public RealyticsReachSettingInput withProducts(JsonNullable<? extends List<IncrementalReachProductInput>> products) {
        Utils.checkNotNull(products, "products");
        this.products = products;
        return this;
    }

    public RealyticsReachSettingInput withRealyticsEntertainmentInput(RealyticsEntertainmentType realyticsEntertainmentInput) {
        Utils.checkNotNull(realyticsEntertainmentInput, "realyticsEntertainmentInput");
        this.realyticsEntertainmentInput = Optional.ofNullable(realyticsEntertainmentInput);
        return this;
    }


    public RealyticsReachSettingInput withRealyticsEntertainmentInput(Optional<? extends RealyticsEntertainmentType> realyticsEntertainmentInput) {
        Utils.checkNotNull(realyticsEntertainmentInput, "realyticsEntertainmentInput");
        this.realyticsEntertainmentInput = realyticsEntertainmentInput;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RealyticsReachSettingInput other = (RealyticsReachSettingInput) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.isActive, other.isActive) &&
            Utils.enhancedDeepEquals(this.products, other.products) &&
            Utils.enhancedDeepEquals(this.realyticsEntertainmentInput, other.realyticsEntertainmentInput);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, name, isActive,
            products, realyticsEntertainmentInput);
    }
    
    @Override
    public String toString() {
        return Utils.toString(RealyticsReachSettingInput.class,
                "id", id,
                "name", name,
                "isActive", isActive,
                "products", products,
                "realyticsEntertainmentInput", realyticsEntertainmentInput);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<Integer> id = Optional.empty();

        private JsonNullable<String> name = JsonNullable.undefined();

        private Optional<Boolean> isActive = Optional.empty();

        private JsonNullable<? extends List<IncrementalReachProductInput>> products = JsonNullable.undefined();

        private Optional<? extends RealyticsEntertainmentType> realyticsEntertainmentInput = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder id(int id) {
            Utils.checkNotNull(id, "id");
            this.id = Optional.ofNullable(id);
            return this;
        }

        public Builder id(Optional<Integer> id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }


        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = JsonNullable.of(name);
            return this;
        }

        public Builder name(JsonNullable<String> name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }


        public Builder isActive(boolean isActive) {
            Utils.checkNotNull(isActive, "isActive");
            this.isActive = Optional.ofNullable(isActive);
            return this;
        }

        public Builder isActive(Optional<Boolean> isActive) {
            Utils.checkNotNull(isActive, "isActive");
            this.isActive = isActive;
            return this;
        }


        public Builder products(List<IncrementalReachProductInput> products) {
            Utils.checkNotNull(products, "products");
            this.products = JsonNullable.of(products);
            return this;
        }

        public Builder products(JsonNullable<? extends List<IncrementalReachProductInput>> products) {
            Utils.checkNotNull(products, "products");
            this.products = products;
            return this;
        }


        public Builder realyticsEntertainmentInput(RealyticsEntertainmentType realyticsEntertainmentInput) {
            Utils.checkNotNull(realyticsEntertainmentInput, "realyticsEntertainmentInput");
            this.realyticsEntertainmentInput = Optional.ofNullable(realyticsEntertainmentInput);
            return this;
        }

        public Builder realyticsEntertainmentInput(Optional<? extends RealyticsEntertainmentType> realyticsEntertainmentInput) {
            Utils.checkNotNull(realyticsEntertainmentInput, "realyticsEntertainmentInput");
            this.realyticsEntertainmentInput = realyticsEntertainmentInput;
            return this;
        }

        public RealyticsReachSettingInput build() {

            return new RealyticsReachSettingInput(
                id, name, isActive,
                products, realyticsEntertainmentInput);
        }

    }
}
