/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum RenderingContext {
    OTHER("Other"),
    IN_APP("InApp"),
    MOBILE_OPTIMIZED_WEB("MobileOptimizedWeb");

    @JsonValue
    private final String value;

    RenderingContext(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<RenderingContext> fromValue(String value) {
        for (RenderingContext o: RenderingContext.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

