/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;

public class StandardJobSubmitResponse {

    /**
     * The ID of the job.
     */
    @JsonProperty("id")
    private long id;

    @JsonCreator
    public StandardJobSubmitResponse(
            @JsonProperty("id") long id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
    }

    /**
     * The ID of the job.
     */
    @JsonIgnore
    public long id() {
        return id;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * The ID of the job.
     */
    public StandardJobSubmitResponse withId(long id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StandardJobSubmitResponse other = (StandardJobSubmitResponse) o;
        return 
            Objects.deepEquals(this.id, other.id);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            id);
    }
    
    @Override
    public String toString() {
        return Utils.toString(StandardJobSubmitResponse.class,
                "id", id);
    }
    
    public final static class Builder {
 
        private Long id;
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The ID of the job.
         */
        public Builder id(long id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }
        
        public StandardJobSubmitResponse build() {
            return new StandardJobSubmitResponse(
                id);
        }
    }
}
