/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapitools.jackson.nullable.JsonNullable;

public class StringWorkflowsOptional {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("value")
    private JsonNullable<String> value;

    @JsonCreator
    public StringWorkflowsOptional(
            @JsonProperty("value") JsonNullable<String> value) {
        Utils.checkNotNull(value, "value");
        this.value = value;
    }
    
    public StringWorkflowsOptional() {
        this(JsonNullable.undefined());
    }

    @JsonIgnore
    public JsonNullable<String> value() {
        return value;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public StringWorkflowsOptional withValue(String value) {
        Utils.checkNotNull(value, "value");
        this.value = JsonNullable.of(value);
        return this;
    }

    public StringWorkflowsOptional withValue(JsonNullable<String> value) {
        Utils.checkNotNull(value, "value");
        this.value = value;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StringWorkflowsOptional other = (StringWorkflowsOptional) o;
        return 
            Objects.deepEquals(this.value, other.value);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            value);
    }
    
    @Override
    public String toString() {
        return Utils.toString(StringWorkflowsOptional.class,
                "value", value);
    }
    
    public final static class Builder {
 
        private JsonNullable<String> value = JsonNullable.undefined();
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder value(String value) {
            Utils.checkNotNull(value, "value");
            this.value = JsonNullable.of(value);
            return this;
        }

        public Builder value(JsonNullable<String> value) {
            Utils.checkNotNull(value, "value");
            this.value = value;
            return this;
        }
        
        public StringWorkflowsOptional build() {
            return new StringWorkflowsOptional(
                value);
        }
    }
}
