/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum TargetingGenderInput {
    MALE("Male"),
    FEMALE("Female"),
    BOTH("Both");

    @JsonValue
    private final String value;

    TargetingGenderInput(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<TargetingGenderInput> fromValue(String value) {
        for (TargetingGenderInput o: TargetingGenderInput.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

