/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum TencentPageQualityInput {
    BLOCK_HIGH_RISK("BlockHighRisk"),
    BLOCK_MODERATE_AND_HIGH_RISK("BlockModerateAndHighRisk");

    @JsonValue
    private final String value;

    TencentPageQualityInput(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<TencentPageQualityInput> fromValue(String value) {
        for (TencentPageQualityInput o: TencentPageQualityInput.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

