/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum VideoQuality {
    UNKNOWN("Unknown"),
    PROFESSIONAL("Professional"),
    PROSUMER("Prosumer"),
    USER_GENERATED("UserGenerated"),
    MIXED("Mixed");

    @JsonValue
    private final String value;

    VideoQuality(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<VideoQuality> fromValue(String value) {
        for (VideoQuality o: VideoQuality.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

