/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum VideoPlaybackType {
    NONE("None"),
    PRE_ROLL("PreRoll"),
    MID_ROLL("MidRoll"),
    POST_ROLL("PostRoll"),
    UNDECLARED("Undeclared"),
    INTERSTITIAL_SLIDER_FLOATING("InterstitialSliderFloating"),
    ACCOMPANYING_CONTENT("AccompanyingContent"),
    STANDALONE("Standalone");

    @JsonValue
    private final String value;

    VideoPlaybackType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<VideoPlaybackType> fromValue(String value) {
        for (VideoPlaybackType o: VideoPlaybackType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

