/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum WeatherCondition {
    THUNDERSTORM("Thunderstorm"),
    DRIZZLE("Drizzle"),
    RAIN("Rain"),
    SNOW("Snow"),
    MIST("Mist"),
    SMOKE("Smoke"),
    HAZE("Haze"),
    DUST("Dust"),
    FOG("Fog"),
    SAND("Sand"),
    ASH("Ash"),
    SQUALL("Squall"),
    TORNADO("Tornado"),
    CLEAR("Clear"),
    CLOUDS("Clouds"),
    WIND("Wind");

    @JsonValue
    private final String value;

    WeatherCondition(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<WeatherCondition> fromValue(String value) {
        for (WeatherCondition o: WeatherCondition.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

