/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.operations;

import static com.thetradedesk.workflows.operations.Operations.RequestOperation;

import com.thetradedesk.workflows.SDKConfiguration;
import com.thetradedesk.workflows.operations.GetJobStatusOperation;
import com.thetradedesk.workflows.utils.Options;
import com.thetradedesk.workflows.utils.RetryConfig;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Exception;
import java.lang.Long;
import java.util.Optional;

public class GetJobStatusRequestBuilder {

    private Long id;
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKConfiguration sdkConfiguration;

    public GetJobStatusRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetJobStatusRequestBuilder id(long id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }
                
    public GetJobStatusRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public GetJobStatusRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }


    private GetJobStatusRequest buildRequest() {

        GetJobStatusRequest request = new GetJobStatusRequest(id);

        return request;
    }

    public GetJobStatusResponse call() throws Exception {
        Optional<Options> options = Optional.of(Options.builder()
            .retryConfig(retryConfig)
            .build());

        RequestOperation<GetJobStatusRequest, GetJobStatusResponse> operation
              = new GetJobStatusOperation(
                 sdkConfiguration,
                 options);
        GetJobStatusRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
