/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.operations;

import com.thetradedesk.workflows.models.components.AdGroupBulkUpdateWorkflowInputWithValidation;
import com.thetradedesk.workflows.utils.Options;
import com.thetradedesk.workflows.utils.RetryConfig;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Exception;
import java.util.Optional;

public class PatchTypebasedjobAdgroupBulkRequestBuilder {

    private Optional<? extends AdGroupBulkUpdateWorkflowInputWithValidation> request = Optional.empty();
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKMethodInterfaces.MethodCallPatchTypebasedjobAdgroupBulk sdk;

    public PatchTypebasedjobAdgroupBulkRequestBuilder(SDKMethodInterfaces.MethodCallPatchTypebasedjobAdgroupBulk sdk) {
        this.sdk = sdk;
    }
                
    public PatchTypebasedjobAdgroupBulkRequestBuilder request(AdGroupBulkUpdateWorkflowInputWithValidation request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public PatchTypebasedjobAdgroupBulkRequestBuilder request(Optional<? extends AdGroupBulkUpdateWorkflowInputWithValidation> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }
                
    public PatchTypebasedjobAdgroupBulkRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public PatchTypebasedjobAdgroupBulkRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }

    public PatchTypebasedjobAdgroupBulkResponse call() throws Exception {
        Optional<Options> options = Optional.of(Options.builder()
                                                    .retryConfig(retryConfig)
                                                    .build());
        return sdk.patchTypebasedjobAdgroupBulk(
            request,
            options);
    }
}
