/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.operations;

import com.thetradedesk.workflows.models.components.CampaignBulkUpdateWorkflowInputWithValidation;
import com.thetradedesk.workflows.utils.Options;
import com.thetradedesk.workflows.utils.RetryConfig;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Exception;
import java.util.Optional;

public class PatchCampaignBulkRequestBuilder {

    private Optional<? extends CampaignBulkUpdateWorkflowInputWithValidation> request = Optional.empty();
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKMethodInterfaces.MethodCallPatchCampaignBulk sdk;

    public PatchCampaignBulkRequestBuilder(SDKMethodInterfaces.MethodCallPatchCampaignBulk sdk) {
        this.sdk = sdk;
    }
                
    public PatchCampaignBulkRequestBuilder request(CampaignBulkUpdateWorkflowInputWithValidation request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public PatchCampaignBulkRequestBuilder request(Optional<? extends CampaignBulkUpdateWorkflowInputWithValidation> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }
                
    public PatchCampaignBulkRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public PatchCampaignBulkRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }

    public PatchCampaignBulkResponse call() throws Exception {
        Optional<Options> options = Optional.of(Options.builder()
                                                    .retryConfig(retryConfig)
                                                    .build());
        return sdk.patchCampaignBulk(
            request,
            options);
    }
}
