/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.thetradedesk.workflows.models.components.BulkJobSubmitResponse;
import com.thetradedesk.workflows.utils.Response;
import com.thetradedesk.workflows.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;

public class PatchCampaignBulkResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Accepted
     */
    private Optional<? extends BulkJobSubmitResponse> bulkJobSubmitResponse;

    @JsonCreator
    public PatchCampaignBulkResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends BulkJobSubmitResponse> bulkJobSubmitResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(bulkJobSubmitResponse, "bulkJobSubmitResponse");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.bulkJobSubmitResponse = bulkJobSubmitResponse;
    }
    
    public PatchCampaignBulkResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * Accepted
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<BulkJobSubmitResponse> bulkJobSubmitResponse() {
        return (Optional<BulkJobSubmitResponse>) bulkJobSubmitResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * HTTP response content type for this operation
     */
    public PatchCampaignBulkResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public PatchCampaignBulkResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public PatchCampaignBulkResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Accepted
     */
    public PatchCampaignBulkResponse withBulkJobSubmitResponse(BulkJobSubmitResponse bulkJobSubmitResponse) {
        Utils.checkNotNull(bulkJobSubmitResponse, "bulkJobSubmitResponse");
        this.bulkJobSubmitResponse = Optional.ofNullable(bulkJobSubmitResponse);
        return this;
    }

    /**
     * Accepted
     */
    public PatchCampaignBulkResponse withBulkJobSubmitResponse(Optional<? extends BulkJobSubmitResponse> bulkJobSubmitResponse) {
        Utils.checkNotNull(bulkJobSubmitResponse, "bulkJobSubmitResponse");
        this.bulkJobSubmitResponse = bulkJobSubmitResponse;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PatchCampaignBulkResponse other = (PatchCampaignBulkResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.bulkJobSubmitResponse, other.bulkJobSubmitResponse);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            bulkJobSubmitResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PatchCampaignBulkResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "bulkJobSubmitResponse", bulkJobSubmitResponse);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends BulkJobSubmitResponse> bulkJobSubmitResponse = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * Accepted
         */
        public Builder bulkJobSubmitResponse(BulkJobSubmitResponse bulkJobSubmitResponse) {
            Utils.checkNotNull(bulkJobSubmitResponse, "bulkJobSubmitResponse");
            this.bulkJobSubmitResponse = Optional.ofNullable(bulkJobSubmitResponse);
            return this;
        }

        /**
         * Accepted
         */
        public Builder bulkJobSubmitResponse(Optional<? extends BulkJobSubmitResponse> bulkJobSubmitResponse) {
            Utils.checkNotNull(bulkJobSubmitResponse, "bulkJobSubmitResponse");
            this.bulkJobSubmitResponse = bulkJobSubmitResponse;
            return this;
        }
        
        public PatchCampaignBulkResponse build() {
            return new PatchCampaignBulkResponse(
                contentType,
                statusCode,
                rawResponse,
                bulkJobSubmitResponse);
        }
    }
}
