/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.operations;

import com.thetradedesk.workflows.utils.Options;
import com.thetradedesk.workflows.utils.RetryConfig;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import java.util.List;
import java.util.Optional;

public class PostCampaignArchiveRequestBuilder {

    private Optional<? extends List<String>> request = Optional.empty();
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKMethodInterfaces.MethodCallPostCampaignArchive sdk;

    public PostCampaignArchiveRequestBuilder(SDKMethodInterfaces.MethodCallPostCampaignArchive sdk) {
        this.sdk = sdk;
    }
                
    public PostCampaignArchiveRequestBuilder request(List<String> request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public PostCampaignArchiveRequestBuilder request(Optional<? extends List<String>> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }
                
    public PostCampaignArchiveRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public PostCampaignArchiveRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }

    public PostCampaignArchiveResponse call() throws Exception {
        Optional<Options> options = Optional.of(Options.builder()
                                                    .retryConfig(retryConfig)
                                                    .build());
        return sdk.postCampaignArchive(
            request,
            options);
    }
}
