/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.thetradedesk.workflows.models.operations;

import com.thetradedesk.workflows.models.components.CampaignCreationInput;
import com.thetradedesk.workflows.utils.Options;
import com.thetradedesk.workflows.utils.RetryConfig;
import com.thetradedesk.workflows.utils.Utils;
import java.util.Optional;

public class PostCampaignRequestBuilder {

    private Optional<? extends CampaignCreationInput> request = Optional.empty();
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKMethodInterfaces.MethodCallPostCampaign sdk;

    public PostCampaignRequestBuilder(SDKMethodInterfaces.MethodCallPostCampaign sdk) {
        this.sdk = sdk;
    }
                
    public PostCampaignRequestBuilder request(CampaignCreationInput request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public PostCampaignRequestBuilder request(Optional<? extends CampaignCreationInput> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }
                
    public PostCampaignRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public PostCampaignRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }

    public PostCampaignResponse call() throws Exception {
        Optional<Options> options = Optional.of(Options.builder()
                                                    .retryConfig(retryConfig)
                                                    .build());
        return sdk.create(
            request,
            options);
    }
}
