/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.thetradedesk.workflows.models.operations;

import com.thetradedesk.workflows.models.components.SeedCreationInput;
import com.thetradedesk.workflows.utils.Options;
import com.thetradedesk.workflows.utils.RetryConfig;
import com.thetradedesk.workflows.utils.Utils;
import java.util.Optional;

public class PostSeedRequestBuilder {

    private Optional<? extends SeedCreationInput> request = Optional.empty();
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKMethodInterfaces.MethodCallPostSeed sdk;

    public PostSeedRequestBuilder(SDKMethodInterfaces.MethodCallPostSeed sdk) {
        this.sdk = sdk;
    }
                
    public PostSeedRequestBuilder request(SeedCreationInput request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public PostSeedRequestBuilder request(Optional<? extends SeedCreationInput> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }
                
    public PostSeedRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public PostSeedRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }

    public PostSeedResponse call() throws Exception {
        Optional<Options> options = Optional.of(Options.builder()
                                                    .retryConfig(retryConfig)
                                                    .build());
        return sdk.create(
            request,
            options);
    }
}
