/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.operations;

import com.thetradedesk.workflows.models.components.FirstPartyDataInput;
import com.thetradedesk.workflows.utils.Options;
import com.thetradedesk.workflows.utils.RetryConfig;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Exception;
import java.util.Optional;

public class PostTypebasedjobFirstpartydataRequestBuilder {

    private Optional<? extends FirstPartyDataInput> request = Optional.empty();
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKMethodInterfaces.MethodCallPostTypebasedjobFirstpartydata sdk;

    public PostTypebasedjobFirstpartydataRequestBuilder(SDKMethodInterfaces.MethodCallPostTypebasedjobFirstpartydata sdk) {
        this.sdk = sdk;
    }
                
    public PostTypebasedjobFirstpartydataRequestBuilder request(FirstPartyDataInput request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public PostTypebasedjobFirstpartydataRequestBuilder request(Optional<? extends FirstPartyDataInput> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }
                
    public PostTypebasedjobFirstpartydataRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public PostTypebasedjobFirstpartydataRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }

    public PostTypebasedjobFirstpartydataResponse call() throws Exception {
        Optional<Options> options = Optional.of(Options.builder()
                                                    .retryConfig(retryConfig)
                                                    .build());
        return sdk.postTypebasedjobFirstpartydata(
            request,
            options);
    }
}
