/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.operations;

import com.thetradedesk.workflows.models.components.AdGroupBulkCreateWorkflowInputWithValidation;
import com.thetradedesk.workflows.models.components.AdGroupBulkUpdateWorkflowInputWithValidation;
import com.thetradedesk.workflows.models.components.AdGroupCreateWorkflowInputWithValidation;
import com.thetradedesk.workflows.models.components.AdGroupUpdateWorkflowInputWithValidation;
import com.thetradedesk.workflows.models.components.CallPubApiWorkflowInput;
import com.thetradedesk.workflows.models.components.CampaignBulkCreateWorkflowInputWithValidation;
import com.thetradedesk.workflows.models.components.CampaignBulkUpdateWorkflowInputWithValidation;
import com.thetradedesk.workflows.models.components.CampaignCreateWorkflowInputWithValidation;
import com.thetradedesk.workflows.models.components.CampaignUpdateWorkflowInputWithValidation;
import com.thetradedesk.workflows.models.components.FirstPartyDataInput;
import com.thetradedesk.workflows.models.components.GraphQLRequestInput;
import com.thetradedesk.workflows.models.components.ThirdPartyDataInput;
import com.thetradedesk.workflows.utils.Options;
import java.lang.Boolean;
import java.lang.Exception;
import java.lang.String;
import java.util.List;
import java.util.Optional;

public class SDKMethodInterfaces {

    public interface MethodCallPostAdgroup {
        PostAdgroupResponse postAdgroup(
            Optional<? extends AdGroupCreateWorkflowInputWithValidation> request,
            Optional<Options> options) throws Exception;
    }

    public interface MethodCallPatchAdgroup {
        PatchAdgroupResponse patchAdgroup(
            Optional<? extends AdGroupUpdateWorkflowInputWithValidation> request,
            Optional<Options> options) throws Exception;
    }

    public interface MethodCallPostAdgroupArchive {
        PostAdgroupArchiveResponse postAdgroupArchive(
            Optional<Boolean> forceArchive,
            Optional<? extends List<String>> requestBody,
            Optional<Options> options) throws Exception;
    }

    public interface MethodCallPostTypebasedjobAdgroupBulk {
        PostTypebasedjobAdgroupBulkResponse postTypebasedjobAdgroupBulk(
            Optional<? extends AdGroupBulkCreateWorkflowInputWithValidation> request,
            Optional<Options> options) throws Exception;
    }

    public interface MethodCallPatchTypebasedjobAdgroupBulk {
        PatchTypebasedjobAdgroupBulkResponse patchTypebasedjobAdgroupBulk(
            Optional<? extends AdGroupBulkUpdateWorkflowInputWithValidation> request,
            Optional<Options> options) throws Exception;
    }

    public interface MethodCallPostCampaign {
        PostCampaignResponse create(
            Optional<? extends CampaignCreateWorkflowInputWithValidation> request,
            Optional<Options> options) throws Exception;
    }

    public interface MethodCallPatchCampaign {
        PatchCampaignResponse patchCampaign(
            Optional<? extends CampaignUpdateWorkflowInputWithValidation> request,
            Optional<Options> options) throws Exception;
    }

    public interface MethodCallPostTypebasedjobCampaignBulk {
        PostTypebasedjobCampaignBulkResponse postTypebasedjobCampaignBulk(
            Optional<? extends CampaignBulkCreateWorkflowInputWithValidation> request,
            Optional<Options> options) throws Exception;
    }

    public interface MethodCallPatchTypebasedjobCampaignBulk {
        PatchTypebasedjobCampaignBulkResponse patchTypebasedjobCampaignBulk(
            Optional<? extends CampaignBulkUpdateWorkflowInputWithValidation> request,
            Optional<Options> options) throws Exception;
    }

    public interface MethodCallPostCampaignArchive {
        PostCampaignArchiveResponse postCampaignArchive(
            Optional<Boolean> forceArchive,
            Optional<? extends List<String>> requestBody,
            Optional<Options> options) throws Exception;
    }

    public interface MethodCallGetCampaignIdVersion {
        GetCampaignIdVersionResponse getVersion(
            String id,
            Optional<Options> options) throws Exception;
    }

    public interface MethodCallPostTypebasedjobFirstpartydata {
        PostTypebasedjobFirstpartydataResponse postTypebasedjobFirstpartydata(
            Optional<? extends FirstPartyDataInput> request,
            Optional<Options> options) throws Exception;
    }

    public interface MethodCallPostGraphqlrequest {
        PostGraphqlrequestResponse postGraphqlrequest(
            Optional<? extends GraphQLRequestInput> request,
            Optional<Options> options) throws Exception;
    }

    public interface MethodCallPostRestrequest {
        PostRestrequestResponse postRestrequest(
            Optional<? extends CallPubApiWorkflowInput> request,
            Optional<Options> options) throws Exception;
    }

    public interface MethodCallPostTypebasedjobThirdpartydata {
        PostTypebasedjobThirdpartydataResponse postTypebasedjobThirdpartydata(
            Optional<? extends ThirdPartyDataInput> request,
            Optional<Options> options) throws Exception;
    }

    public interface MethodCallGetTypebasedjobIdStatus {
        GetTypebasedjobIdStatusResponse getTypebasedjobIdStatus(
            long id,
            Optional<Options> options) throws Exception;
    }
}
