/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.thetradedesk.workflows.utils.Utils;
import java.lang.Override;
import java.lang.String;

/**
 * SubmitRestRequestResponseBody
 * 
 * <p>OK
 */
public class SubmitRestRequestResponseBody {
    @JsonCreator
    public SubmitRestRequestResponseBody() {
    }

    public static Builder builder() {
        return new Builder();
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        return true;
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            );
    }
    
    @Override
    public String toString() {
        return Utils.toString(SubmitRestRequestResponseBody.class);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Builder() {
          // force use of static builder() method
        }

        public SubmitRestRequestResponseBody build() {

            return new SubmitRestRequestResponseBody(
                );
        }

    }
}
