/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows;

import static com.thetradedesk.workflows.operations.Operations.AsyncRequestOperation;

import com.thetradedesk.workflows.models.operations.GetGraphQlQueryJobStatusRequest;
import com.thetradedesk.workflows.models.operations.GetJobStatusRequest;
import com.thetradedesk.workflows.models.operations.async.GetGraphQlQueryJobStatusRequestBuilder;
import com.thetradedesk.workflows.models.operations.async.GetGraphQlQueryJobStatusResponse;
import com.thetradedesk.workflows.models.operations.async.GetJobStatusRequestBuilder;
import com.thetradedesk.workflows.models.operations.async.GetJobStatusResponse;
import com.thetradedesk.workflows.operations.GetGraphQlQueryJobStatus;
import com.thetradedesk.workflows.operations.GetJobStatus;
import com.thetradedesk.workflows.utils.Options;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;


public class AsyncJobStatus {
    private final SDKConfiguration sdkConfiguration;
    private final JobStatus syncSDK;

    AsyncJobStatus(JobStatus syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public JobStatus sync() {
        return syncSDK;
    }


    /**
     * Get the status of a previously submitted GraphQL query job
     * 
     * <p>Use this operation to get a previously submitted GraphQL query job's status and completion percentage.
     * Once a job is complete, this operation will return the URL from which to download the job results.
     * 
     * @return The async call builder
     */
    public GetGraphQlQueryJobStatusRequestBuilder getGraphQlQueryJobStatus() {
        return new GetGraphQlQueryJobStatusRequestBuilder(sdkConfiguration);
    }

    /**
     * Get the status of a previously submitted GraphQL query job
     * 
     * <p>Use this operation to get a previously submitted GraphQL query job's status and completion percentage.
     * Once a job is complete, this operation will return the URL from which to download the job results.
     * 
     * @param id 
     * @return CompletableFuture&lt;GetGraphQlQueryJobStatusResponse&gt; - The async response
     */
    public CompletableFuture<GetGraphQlQueryJobStatusResponse> getGraphQlQueryJobStatus(String id) {
        return getGraphQlQueryJobStatus(id, Optional.empty());
    }

    /**
     * Get the status of a previously submitted GraphQL query job
     * 
     * <p>Use this operation to get a previously submitted GraphQL query job's status and completion percentage.
     * Once a job is complete, this operation will return the URL from which to download the job results.
     * 
     * @param id 
     * @param options additional options
     * @return CompletableFuture&lt;GetGraphQlQueryJobStatusResponse&gt; - The async response
     */
    public CompletableFuture<GetGraphQlQueryJobStatusResponse> getGraphQlQueryJobStatus(String id, Optional<Options> options) {
        GetGraphQlQueryJobStatusRequest request =
            GetGraphQlQueryJobStatusRequest
                .builder()
                .id(id)
                .build();
        AsyncRequestOperation<GetGraphQlQueryJobStatusRequest, GetGraphQlQueryJobStatusResponse> operation
              = new GetGraphQlQueryJobStatus.Async(sdkConfiguration, options, sdkConfiguration.retryScheduler());
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get the status of a previously submitted job
     * 
     * <p>Use this operation to get a previously submitted job's status and completion percentage.
     * Once a job is complete, this operation will return the URL from which to download the job results.
     * 
     * <p>Job results expire after 24 hours, at which point you will need to submit a new job.
     * 
     * @return The async call builder
     */
    public GetJobStatusRequestBuilder getJobStatus() {
        return new GetJobStatusRequestBuilder(sdkConfiguration);
    }

    /**
     * Get the status of a previously submitted job
     * 
     * <p>Use this operation to get a previously submitted job's status and completion percentage.
     * Once a job is complete, this operation will return the URL from which to download the job results.
     * 
     * <p>Job results expire after 24 hours, at which point you will need to submit a new job.
     * 
     * @param id 
     * @return CompletableFuture&lt;GetJobStatusResponse&gt; - The async response
     */
    public CompletableFuture<GetJobStatusResponse> getJobStatus(long id) {
        return getJobStatus(id, Optional.empty());
    }

    /**
     * Get the status of a previously submitted job
     * 
     * <p>Use this operation to get a previously submitted job's status and completion percentage.
     * Once a job is complete, this operation will return the URL from which to download the job results.
     * 
     * <p>Job results expire after 24 hours, at which point you will need to submit a new job.
     * 
     * @param id 
     * @param options additional options
     * @return CompletableFuture&lt;GetJobStatusResponse&gt; - The async response
     */
    public CompletableFuture<GetJobStatusResponse> getJobStatus(long id, Optional<Options> options) {
        GetJobStatusRequest request =
            GetJobStatusRequest
                .builder()
                .id(id)
                .build();
        AsyncRequestOperation<GetJobStatusRequest, GetJobStatusResponse> operation
              = new GetJobStatus.Async(sdkConfiguration, options, sdkConfiguration.retryScheduler());
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
