/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows;

import static com.thetradedesk.workflows.operations.Operations.AsyncRequestOperation;

import com.thetradedesk.workflows.models.components.CampaignBulkCreateWorkflowInputWithValidation;
import com.thetradedesk.workflows.models.components.CampaignBulkUpdateWorkflowInputWithValidation;
import com.thetradedesk.workflows.models.components.CampaignCreateWorkflowInputWithValidation;
import com.thetradedesk.workflows.models.components.CampaignUpdateWorkflowInputWithValidation;
import com.thetradedesk.workflows.models.operations.ArchiveCampaignsRequest;
import com.thetradedesk.workflows.models.operations.GetCampaignVersionRequest;
import com.thetradedesk.workflows.models.operations.async.ArchiveCampaignsRequestBuilder;
import com.thetradedesk.workflows.models.operations.async.ArchiveCampaignsResponse;
import com.thetradedesk.workflows.models.operations.async.CreateCampaignRequestBuilder;
import com.thetradedesk.workflows.models.operations.async.CreateCampaignResponse;
import com.thetradedesk.workflows.models.operations.async.CreateCampaignsJobRequestBuilder;
import com.thetradedesk.workflows.models.operations.async.CreateCampaignsJobResponse;
import com.thetradedesk.workflows.models.operations.async.GetCampaignVersionRequestBuilder;
import com.thetradedesk.workflows.models.operations.async.GetCampaignVersionResponse;
import com.thetradedesk.workflows.models.operations.async.UpdateCampaignRequestBuilder;
import com.thetradedesk.workflows.models.operations.async.UpdateCampaignResponse;
import com.thetradedesk.workflows.models.operations.async.UpdateCampaignsJobRequestBuilder;
import com.thetradedesk.workflows.models.operations.async.UpdateCampaignsJobResponse;
import com.thetradedesk.workflows.operations.ArchiveCampaigns;
import com.thetradedesk.workflows.operations.CreateCampaign;
import com.thetradedesk.workflows.operations.CreateCampaignsJob;
import com.thetradedesk.workflows.operations.GetCampaignVersion;
import com.thetradedesk.workflows.operations.UpdateCampaign;
import com.thetradedesk.workflows.operations.UpdateCampaignsJob;
import com.thetradedesk.workflows.utils.Headers;
import com.thetradedesk.workflows.utils.Options;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;


public class AsyncCampaign {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Campaign syncSDK;

    AsyncCampaign(Campaign syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Campaign sync() {
        return syncSDK;
    }


    /**
     * Create a new campaign
     * 
     * @return The async call builder
     */
    public CreateCampaignRequestBuilder create() {
        return new CreateCampaignRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a new campaign
     * 
     * @return {@code CompletableFuture<CreateCampaignResponse>} - The async response
     */
    public CompletableFuture<CreateCampaignResponse> createDirect() {
        return create(Optional.empty(), Optional.empty());
    }

    /**
     * Create a new campaign
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<CreateCampaignResponse>} - The async response
     */
    public CompletableFuture<CreateCampaignResponse> create(Optional<? extends CampaignCreateWorkflowInputWithValidation> request, Optional<Options> options) {
        AsyncRequestOperation<Optional<? extends CampaignCreateWorkflowInputWithValidation>, CreateCampaignResponse> operation
              = new CreateCampaign.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Update a campaign
     * 
     * <p>Only the fields provided in the request payload will be updated.
     * 
     * @return The async call builder
     */
    public UpdateCampaignRequestBuilder updateCampaign() {
        return new UpdateCampaignRequestBuilder(sdkConfiguration);
    }

    /**
     * Update a campaign
     * 
     * <p>Only the fields provided in the request payload will be updated.
     * 
     * @return {@code CompletableFuture<UpdateCampaignResponse>} - The async response
     */
    public CompletableFuture<UpdateCampaignResponse> updateCampaignDirect() {
        return updateCampaign(Optional.empty(), Optional.empty());
    }

    /**
     * Update a campaign
     * 
     * <p>Only the fields provided in the request payload will be updated.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<UpdateCampaignResponse>} - The async response
     */
    public CompletableFuture<UpdateCampaignResponse> updateCampaign(Optional<? extends CampaignUpdateWorkflowInputWithValidation> request, Optional<Options> options) {
        AsyncRequestOperation<Optional<? extends CampaignUpdateWorkflowInputWithValidation>, UpdateCampaignResponse> operation
              = new UpdateCampaign.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Submit a job to create multiple new campaigns
     * 
     * @return The async call builder
     */
    public CreateCampaignsJobRequestBuilder createCampaignsJob() {
        return new CreateCampaignsJobRequestBuilder(sdkConfiguration);
    }

    /**
     * Submit a job to create multiple new campaigns
     * 
     * @return {@code CompletableFuture<CreateCampaignsJobResponse>} - The async response
     */
    public CompletableFuture<CreateCampaignsJobResponse> createCampaignsJobDirect() {
        return createCampaignsJob(Optional.empty(), Optional.empty());
    }

    /**
     * Submit a job to create multiple new campaigns
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<CreateCampaignsJobResponse>} - The async response
     */
    public CompletableFuture<CreateCampaignsJobResponse> createCampaignsJob(Optional<? extends CampaignBulkCreateWorkflowInputWithValidation> request, Optional<Options> options) {
        AsyncRequestOperation<Optional<? extends CampaignBulkCreateWorkflowInputWithValidation>, CreateCampaignsJobResponse> operation
              = new CreateCampaignsJob.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Submit a job to update multiple campaigns
     * 
     * <p>Only the fields provided in the request payload for each specific campaign will be updated.
     * 
     * @return The async call builder
     */
    public UpdateCampaignsJobRequestBuilder updateCampaignsJob() {
        return new UpdateCampaignsJobRequestBuilder(sdkConfiguration);
    }

    /**
     * Submit a job to update multiple campaigns
     * 
     * <p>Only the fields provided in the request payload for each specific campaign will be updated.
     * 
     * @return {@code CompletableFuture<UpdateCampaignsJobResponse>} - The async response
     */
    public CompletableFuture<UpdateCampaignsJobResponse> updateCampaignsJobDirect() {
        return updateCampaignsJob(Optional.empty(), Optional.empty());
    }

    /**
     * Submit a job to update multiple campaigns
     * 
     * <p>Only the fields provided in the request payload for each specific campaign will be updated.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<UpdateCampaignsJobResponse>} - The async response
     */
    public CompletableFuture<UpdateCampaignsJobResponse> updateCampaignsJob(Optional<? extends CampaignBulkUpdateWorkflowInputWithValidation> request, Optional<Options> options) {
        AsyncRequestOperation<Optional<? extends CampaignBulkUpdateWorkflowInputWithValidation>, UpdateCampaignsJobResponse> operation
              = new UpdateCampaignsJob.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Archive multiple campaigns
     * 
     * <p>**NOTE**: Once archived, campaigns cannot be un-archived.
     * 
     * @return The async call builder
     */
    public ArchiveCampaignsRequestBuilder archiveCampaigns() {
        return new ArchiveCampaignsRequestBuilder(sdkConfiguration);
    }

    /**
     * Archive multiple campaigns
     * 
     * <p>**NOTE**: Once archived, campaigns cannot be un-archived.
     * 
     * @return {@code CompletableFuture<ArchiveCampaignsResponse>} - The async response
     */
    public CompletableFuture<ArchiveCampaignsResponse> archiveCampaignsDirect() {
        return archiveCampaigns(Optional.empty(), Optional.empty(), Optional.empty());
    }

    /**
     * Archive multiple campaigns
     * 
     * <p>**NOTE**: Once archived, campaigns cannot be un-archived.
     * 
     * @param forceArchive 
     * @param requestBody 
     * @param options additional options
     * @return {@code CompletableFuture<ArchiveCampaignsResponse>} - The async response
     */
    public CompletableFuture<ArchiveCampaignsResponse> archiveCampaigns(
            Optional<Boolean> forceArchive, Optional<? extends List<String>> requestBody,
            Optional<Options> options) {
        ArchiveCampaignsRequest request =
            ArchiveCampaignsRequest
                .builder()
                .forceArchive(forceArchive)
                .requestBody(requestBody)
                .build();
        AsyncRequestOperation<ArchiveCampaignsRequest, ArchiveCampaignsResponse> operation
              = new ArchiveCampaigns.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get a campaign's version
     * 
     * @return The async call builder
     */
    public GetCampaignVersionRequestBuilder getVersion() {
        return new GetCampaignVersionRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a campaign's version
     * 
     * @param id 
     * @return {@code CompletableFuture<GetCampaignVersionResponse>} - The async response
     */
    public CompletableFuture<GetCampaignVersionResponse> getVersion(String id) {
        return getVersion(id, Optional.empty());
    }

    /**
     * Get a campaign's version
     * 
     * @param id 
     * @param options additional options
     * @return {@code CompletableFuture<GetCampaignVersionResponse>} - The async response
     */
    public CompletableFuture<GetCampaignVersionResponse> getVersion(String id, Optional<Options> options) {
        GetCampaignVersionRequest request =
            GetCampaignVersionRequest
                .builder()
                .id(id)
                .build();
        AsyncRequestOperation<GetCampaignVersionRequest, GetCampaignVersionResponse> operation
              = new GetCampaignVersion.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
