/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows;

import static com.thetradedesk.workflows.operations.Operations.RequestOperation;

import com.thetradedesk.workflows.models.components.CallRestApiWorkflowInput;
import com.thetradedesk.workflows.models.operations.SubmitRestRequestRequestBuilder;
import com.thetradedesk.workflows.models.operations.SubmitRestRequestResponse;
import com.thetradedesk.workflows.operations.SubmitRestRequest;
import com.thetradedesk.workflows.utils.Options;
import java.lang.Exception;
import java.util.Optional;


public class RESTRequest {
    private final SDKConfiguration sdkConfiguration;
    private final AsyncRESTRequest asyncSDK;

    RESTRequest(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncRESTRequest(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncRESTRequest async() {
        return asyncSDK;
    }

    /**
     * Submit a valid REST request
     * 
     * <p>This generic operation can be used to execute any valid REST request.
     * To explore the available REST operations, see the [REST API Reference](https://partner.thetradedesk.com/v3/portal/api/doc/ApiReferencePlatform).
     * 
     * @return The call builder
     */
    public SubmitRestRequestRequestBuilder submitRestRequest() {
        return new SubmitRestRequestRequestBuilder(sdkConfiguration);
    }

    /**
     * Submit a valid REST request
     * 
     * <p>This generic operation can be used to execute any valid REST request.
     * To explore the available REST operations, see the [REST API Reference](https://partner.thetradedesk.com/v3/portal/api/doc/ApiReferencePlatform).
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public SubmitRestRequestResponse submitRestRequestDirect() throws Exception {
        return submitRestRequest(Optional.empty(), Optional.empty());
    }

    /**
     * Submit a valid REST request
     * 
     * <p>This generic operation can be used to execute any valid REST request.
     * To explore the available REST operations, see the [REST API Reference](https://partner.thetradedesk.com/v3/portal/api/doc/ApiReferencePlatform).
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public SubmitRestRequestResponse submitRestRequest(Optional<? extends CallRestApiWorkflowInput> request, Optional<Options> options) throws Exception {
        RequestOperation<Optional<? extends CallRestApiWorkflowInput>, SubmitRestRequestResponse> operation
              = new SubmitRestRequest.Sync(sdkConfiguration, options);
        return operation.handleResponse(operation.doRequest(request));
    }

}
