/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.thetradedesk.workflows.operations;

import static com.thetradedesk.workflows.operations.Operations.RequestOperation;

import com.fasterxml.jackson.core.type.TypeReference;
import com.thetradedesk.workflows.SDKConfiguration;
import com.thetradedesk.workflows.SecuritySource;
import com.thetradedesk.workflows.models.components.CampaignBulkUpdateWorkflowInputWithValidation;
import com.thetradedesk.workflows.models.components.StandardJobSubmitResponse;
import com.thetradedesk.workflows.models.errors.APIException;
import com.thetradedesk.workflows.models.errors.ProblemDetailsException;
import com.thetradedesk.workflows.models.operations.UpdateCampaignsJobResponse;
import com.thetradedesk.workflows.utils.BackoffStrategy;
import com.thetradedesk.workflows.utils.HTTPClient;
import com.thetradedesk.workflows.utils.HTTPRequest;
import com.thetradedesk.workflows.utils.Hook.AfterErrorContextImpl;
import com.thetradedesk.workflows.utils.Hook.AfterSuccessContextImpl;
import com.thetradedesk.workflows.utils.Hook.BeforeRequestContextImpl;
import com.thetradedesk.workflows.utils.Options;
import com.thetradedesk.workflows.utils.Retries.NonRetryableException;
import com.thetradedesk.workflows.utils.Retries;
import com.thetradedesk.workflows.utils.RetryConfig;
import com.thetradedesk.workflows.utils.SerializedBody;
import com.thetradedesk.workflows.utils.Utils.JsonShape;
import com.thetradedesk.workflows.utils.Utils;
import java.io.InputStream;
import java.lang.Exception;
import java.lang.Object;
import java.lang.String;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.TimeUnit;


public class UpdateCampaignsJobOperation implements RequestOperation<Optional<? extends CampaignBulkUpdateWorkflowInputWithValidation>, UpdateCampaignsJobResponse> {
    
    private final SDKConfiguration sdkConfiguration;
    private final Optional<Options> options;

    public UpdateCampaignsJobOperation(
            SDKConfiguration sdkConfiguration,
            Optional<Options> options) {
        this.sdkConfiguration = sdkConfiguration;
        this.options = options;
    }
    
    @Override
    public HttpResponse<InputStream> doRequest(Optional<? extends CampaignBulkUpdateWorkflowInputWithValidation> request) throws Exception {
        options.ifPresent(o -> o.validate(List.of(Options.Option.RETRY_CONFIG)));
        String baseUrl = this.sdkConfiguration.serverUrl();
        String url = Utils.generateURL(
                baseUrl,
                "/standardjob/campaign/bulk");
        
        HTTPRequest req = new HTTPRequest(url, "PATCH");
        Object convertedRequest = Utils.convertToShape(
                request, 
                JsonShape.DEFAULT,
                new TypeReference<Optional<? extends CampaignBulkUpdateWorkflowInputWithValidation>>() {});
        SerializedBody serializedRequestBody = Utils.serializeRequestBody(
                convertedRequest, 
                "request",
                "json",
                false);
        req.setBody(Optional.ofNullable(serializedRequestBody));
        req.addHeader("Accept", "application/json")
            .addHeader("user-agent", 
                SDKConfiguration.USER_AGENT);
        
        Optional<SecuritySource> hookSecuritySource = Optional.of(this.sdkConfiguration.securitySource());
        Utils.configureSecurity(req,  
                this.sdkConfiguration.securitySource().getSecurity());
        HTTPClient client = this.sdkConfiguration.client();
        HTTPRequest finalReq = req;
        RetryConfig retryConfig = options
                .flatMap(Options::retryConfig)
                .or(this.sdkConfiguration::retryConfig)
                .orElse(RetryConfig.builder()
                        .backoff(BackoffStrategy.builder()
                            .initialInterval(500, TimeUnit.MILLISECONDS)
                            .maxInterval(60000, TimeUnit.MILLISECONDS)
                            .baseFactor((double)(1.5))
                            .maxElapsedTime(3600000, TimeUnit.MILLISECONDS)
                            .retryConnectError(true)
                            .build())
                        .build());
        List<String> statusCodes = new ArrayList<>();
        statusCodes.add("5XX");
        Retries retries = Retries.builder()
            .action(() -> {
                HttpRequest r = null;
                try {
                    r = sdkConfiguration.hooks()
                        .beforeRequest(
                            new BeforeRequestContextImpl(
                                this.sdkConfiguration,
                                baseUrl,
                                "updateCampaignsJob", 
                                java.util.Optional.of(java.util.List.of()), 
                                hookSecuritySource),
                            finalReq.build());
                } catch (Exception e) {
                    throw new NonRetryableException(e);
                }
                try {
                    return client.send(r);
                } catch (Exception e) {
                    return sdkConfiguration.hooks()
                        .afterError(
                            new AfterErrorContextImpl(
                                this.sdkConfiguration,
                                baseUrl,
                                "updateCampaignsJob",
                                 java.util.Optional.of(java.util.List.of()),
                                 hookSecuritySource), 
                            Optional.empty(),
                            Optional.of(e));
                }
            })
            .retryConfig(retryConfig)
            .statusCodes(statusCodes)
            .build();
        HttpResponse<InputStream> httpRes = sdkConfiguration.hooks()
                 .afterSuccess(
                     new AfterSuccessContextImpl(
                         this.sdkConfiguration,
                          baseUrl,
                         "updateCampaignsJob", 
                         java.util.Optional.of(java.util.List.of()), 
                         hookSecuritySource),
                     retries.run());
    
        return httpRes;
    }

    @Override
    public UpdateCampaignsJobResponse handleResponse(HttpResponse<InputStream> response) throws Exception {
        String contentType = response
            .headers()
            .firstValue("Content-Type")
            .orElse("application/octet-stream");
        UpdateCampaignsJobResponse.Builder resBuilder = 
            UpdateCampaignsJobResponse
                .builder()
                .contentType(contentType)
                .statusCode(response.statusCode())
                .rawResponse(response);

        UpdateCampaignsJobResponse res = resBuilder.build();
        
        if (Utils.statusCodeMatches(response.statusCode(), "202")) {
            if (Utils.contentTypeMatches(contentType, "application/json")) {
                StandardJobSubmitResponse out = Utils.mapper().readValue(
                    response.body(),
                    new TypeReference<>() {
                    });
                res.withStandardJobSubmitResponse(out);
                return res;
            } else {
                throw new APIException(
                    response, 
                    response.statusCode(), 
                    "Unexpected content-type received: " + contentType, 
                    Utils.extractByteArrayFromBody(response));
            }
        }
        if (Utils.statusCodeMatches(response.statusCode(), "400", "403")) {
            if (Utils.contentTypeMatches(contentType, "application/json")) {
                ProblemDetailsException out = Utils.mapper().readValue(
                    response.body(),
                    new TypeReference<>() {
                    });
                throw out;
            } else {
                throw new APIException(
                    response, 
                    response.statusCode(), 
                    "Unexpected content-type received: " + contentType, 
                    Utils.extractByteArrayFromBody(response));
            }
        }
        if (Utils.statusCodeMatches(response.statusCode(), "4XX")) {
            // no content 
            throw new APIException(
                    response, 
                    response.statusCode(), 
                    "API error occurred", 
                    Utils.extractByteArrayFromBody(response));
        }
        if (Utils.statusCodeMatches(response.statusCode(), "500", "503", "5XX")) {
            // no content 
            throw new APIException(
                    response, 
                    response.statusCode(), 
                    "API error occurred", 
                    Utils.extractByteArrayFromBody(response));
        }
        throw new APIException(
            response, 
            response.statusCode(), 
            "Unexpected status code received: " + response.statusCode(), 
            Utils.extractByteArrayFromBody(response));
    }
}
